### PR TITLE
[jsk_tools] Add delay_timestamp.py

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/jsk-ros-pkg/jsk_recognition/pull/1288

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge.

**Comment by k-okada** [comment]
you do not have to pass msg type, see http://wiki.ros.org/topic_tools

**Comment by wkentaro** [comment]
I updated the commit.

**Comment by k-okada** [comment]
by the way , when you use this tool? I though we do not need this is you crony all computers and use message filter.

**Comment by wkentaro** [comment]
This is not for demo, but test for nodes which uses message_filters.
like: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1288

**Comment by wkentaro** [comment]
@k-okada 
PS. 英語のtypoをもう少し減らしていただけると読みやすくて助かります。。

**Comment by k-okada** [comment]
add ros::warn to describe this is just for test code

--
◉ Kei Okada

**Comment by wkentaro** [comment]
instead of that, why don't we add doc for it?

**Comment by k-okada** [comment]
doc is ok, but people who use this without knowing this is designed for the
system never reads the doc.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
what do you mean with 'the system'?

2015年11月10日火曜日、Kei Okada<notifications@github.com>さんは書きました:

> doc is ok, but people who use this without knowing this is designed for the
> system never reads the doc.
>
> --
> ◉ Kei Okada
>
>
> On Tue, Nov 10, 2015 at 10:25 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > instead of that, why don't we add doc for it?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/pull/1216#issuecomment-155418048
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1216#issuecomment-155419293>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
and why they use this node without reading doc or code?

if you worry about the specific use case, we can create a new package
'jsk_test_tools' as jsk_topic_tools.

2015年11月10日火曜日、Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> what do you mean with 'the system'?
>
> 2015年11月10日火曜日、Kei Okada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> doc is ok, but people who use this without knowing this is designed for
>> the
>> system never reads the doc.
>>
>> --
>> ◉ Kei Okada
>>
>>
>> On Tue, Nov 10, 2015 at 10:25 PM, Kentaro Wada <notifications@github.com>
>> wrote:
>>
>> > instead of that, why don't we add doc for it?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/jsk-ros-pkg/jsk_common/pull/1216#issuecomment-155418048
>> >
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsk-ros-pkg/jsk_common/pull/1216#issuecomment-155419293>
>> .
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
system means everything but test code

--
◉ Kei Okada

**Comment by k-okada** [comment]
On Tue, Nov 10, 2015 at 10:40 PM, Kentaro Wada <notifications@github.com>
wrote:

> and why they use this node without reading doc or code?
>

because the node exists.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
> because the node exists.

because the node is necessary for their system, isn't it? If so, they should read the documentation (or code).

**Comment by k-okada** [comment]
they somehow find the node and misinterpret the usage, I'm pretty sure that
someone will use this node to avoid timestamp problem in next 6 month,
believe me.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
So you mean they misunderstand this as substitute for topic_tools/throttle.

I think I understand your concern, and I'd like to avoid that possibility by putting it another package. could I create a new package? (jsk_test_tools) to serve nodes for test like
jsk_tools/test_stdout.py.

**Comment by k-okada** [comment]
people who do not read document will think this is a magic node that solves
all tf problem, so crating new package did not solve, just print out BIG
warning message.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Okay.
I believe your idea from experience,
and will add warning message.

Maybe that kind of people overlook the warning message, so you say BIG ;)

2015年11月10日火曜日、Kei Okada<notifications@github.com>さんは書きました:

> people who do not read document will think this is a magic node that solves
> all tf problem, so crating new package did not solve, just print out BIG
> warning message.
>
> --
> ◉ Kei Okada
>
>
> On Tue, Nov 10, 2015 at 11:03 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > So you mean they misunderstand this as substitute for
> topic_tools/throttle.
> >
> > I think I understand your concern, and I'd like to avoid that possibility
> > by putting it another package. could I create a new package?
> > (jsk_test_tools) to serve nodes for test like
> > jsk_tools/test_stdout.py.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/pull/1216#issuecomment-155428013
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1216#issuecomment-155429192>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
I added the warning message.
image

**Comment by k-okada** [comment]
thank you

**Comment by wkentaro** [comment]
Please merge.

**Pull request merged**
