### PR TITLE
[image_view2] Visualize label image to rgb

### PR DESCRIPTION
**Pull request by wkentaro**
**depends on https://github.com/jsk-ros-pkg/jsk_recognition/pull/1319**

image

### CODE REVIEW

**Comment by wkentaro** [comment]
need to wait for release of jsk_recognition_utils
```

[image_view2] /workspace/ros/ws_jsk_common/src/jsk_common/jsk_ros_patch/image_view2/image_view2.cpp: In member function 'void image_view2::ImageView2::imageCb(const ImageConstPtr&)': 

[image_view2] /workspace/ros/ws_jsk_common/src/jsk_common/jsk_ros_patch/image_view2/image_view2.cpp:1184:9: error: 'labelToRGB' is not a member of 'jsk_recognition_utils' 

[image_view2]          jsk_recognition_utils::labelToRGB(input_image, original_image_); 

[image_view2]          ^                                                        

[image_view2] Linking CXX executable /workspace/ros/ws_jsk_common/devel/lib/image_view2/points_rectangle_extractor 

[image_view2] [100%] Built target points_rectangle_extractor                    

[jsk_topic_tools] Scanning dependencies of target mux                           

[jsk_topic_tools] [  9%] Building CXX object CMakeFiles/mux.dir/mux.cpp.o       

[jsk_topic_tools] Scanning dependencies of target passthrough                   

[jsk_topic_tools] [ 11%] Building CXX object CMakeFiles/passthrough.dir/passthrough.cpp.o 

[image_view2] make[2]: *** [CMakeFiles/image_view2.dir/image_view2.cpp.o] Error 1 

[image_view2] make[1]: *** [CMakeFiles/image_view2.dir/all] Error 2             

[image_view2] make: *** [all] Error 2                                           

[image_view2] <== '/workspace/ros/ws_jsk_common/build/image_view2/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2' 

```

**Comment by garaemon** [comment]
this is intermediate dependency between different repositories.

labelToRGB should defined in image_view2

**Comment by wkentaro** [comment]
> this is intermediate dependency between different repositories.

what do you mean? You mean packages in `jsk-ros-pkg/jsk_common` should not depend on ones in `jsk-ros-pkg/jsk_recognition`?

`jsk_recognition_utils` does not depends on `image_view2` so I think it works.
```
rospack depends jsk_recognition_utils | grep image_view2 
```

**Comment by garaemon** [comment]
I think bidirectional dependency has cold-start problem.
jsk_common <-> jsk_recognition

**Comment by wkentaro** [comment]
hmm, I see, I will try put labelToRGB to more upstream.

**Comment by wkentaro** [comment]
maybe cv_bridge or image_view.

**Pull request closed without merging**
