### PR TITLE
[jsk_data] Add jsk_data command

### PR DESCRIPTION
**Pull request by wkentaro**
Closes: https://github.com/jsk-ros-pkg/jsk_common/issues/1108
Closes: https://github.com/jsk-ros-pkg/jsk_common/issues/1114

**Before merge**
- [x] remove jsk_data shell func in jsk_data
- [x] synchronization between public dir and Google Drive
- [x] remove Makefile
- [ ] review

**After merge**
- [ ] move large&small to private/

### CODE REVIEW

**Comment by wkentaro** [comment]
jskdata

**Comment by wkentaro** [comment]
jskdata_public

**Comment by wkentaro** [comment]
```
% jskdata
Usage: jskdata [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  get  Download specified file.
  ls   Get list of files.
  put  Upload file to aries.
% jskdata ls -h
Usage: jskdata ls [OPTIONS] [QUERY]

  Get list of files.

Options:
  -p, --public                    Handle public files.
  -s, --show-size                 Display size.
  --sort [time|size|extension|version]
                                  Sort by ..
  -r, --reverse                   Reverse the order.
  -h, --help                      Show this message and exit.
% jskdata get -h
Usage: jskdata get [OPTIONS] QUERY

  Download specified file.

Options:
  -p, --public  Handle public files.
  -h, --help    Show this message and exit.
% jskdata put -h
Usage: jskdata put [OPTIONS] FILENAME

  Upload file to aries.

Options:
  -p, --public  Handle public files.
  -h, --help    Show this message and exit.
```

**Comment by garaemon** [comment]
Why not the name of the command `jsk_data`?

**Comment by wkentaro** [comment]
just make the command easy to type. If you mind I will change.

**Comment by garaemon** [comment]
I think different names are a little bit confusing

**Comment by wkentaro** [comment]
Re-changed command name jskdata -> jsk_data.

**Comment by wkentaro** [comment]
Travis fails:
```
======================================================================
ERROR: Failure: ImportError (No module named freezegun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/test/test_util.py", line 7, in <module>
    from freezegun import freeze_time
ImportError: No module named freezegun
```

but it is defined in package.xml

https://github.com/wkentaro/jsk_common/commit/b4e8f4bfc4f120166577b27555ea56e6fb4ef02b#diff-6fe83a33c8f4787b3766dacbf4fa5cdfR10
```
% rosdep resolve python-freezegun-pip
#pip
freezegun
```

**Comment by wkentaro** [comment]
that seems bug of rosdep.

**Comment by wkentaro** [comment]
@garaemon
The travis test passed, so please review and merge.
After this PR is merged, I will
**move large&small to private/**

**Comment by garaemon** [comment]
jsk_data/src/jsk_data_r is required?

**Comment by wkentaro** [comment]
not required. just to make it contributorr friendly.

**Comment by wkentaro** [comment]
they can run 
```
./jsk_data_r ls
./jsk_data_r get
```
without `catkin bt` many times.

**Comment by garaemon** [comment]
jsk_data/scripts/jsk_data is same?

**Comment by wkentaro** [comment]
That is required. It is moved at build time to global bin.
at here: https://github.com/jsk-ros-pkg/jsk_common/pull/1120/files#diff-df574a402deb668bd7ffc7d00110994eR8

**Comment by garaemon** [comment]
jsk_data and jsk_data_r look same. I think jsk_data_r is not needed.

can paramiko take .ssh/config into account?

**Comment by wkentaro** [comment]
> jsk_data and jsk_data_r look same. 

But the path is different. jsk_data_r is in same dir as jsk_data python package.
So, jsk_data_r see the local jsk_data when `import jsk_data`, but jsk_data which is in script/ does see global one.

**Comment by garaemon** [comment]
I cannot imagine we use this script without `catkin build`. Because jsk_data dependency is not so heavy.

**Comment by wkentaro** [comment]
The script is used by only the contributor of jsk_data python package.
If they edit the src/jsk_data/*.py, they should want to try `$ jsk_data`, but  they cannot without `catkin bt` in each time after editing it.

**Comment by wkentaro** [comment]
> can paramiko take .ssh/config into account?

do you mean if paramiko can see the Hostname in .ssh/config, they can login to aries without SSH_USER env variable?

**Comment by wkentaro** [comment]
> The script is used by only the contributor of jsk_data python package.
If they edit the src/jsk_data/*.py, they should want to try $ jsk_data, but they cannot without catkin bt in each time after editing it.
...

Of course the contributor can copy scripts/jsk_data to src/jsk_data_r at his working, 
but it is troublesome for me personally.

**Comment by garaemon** [comment]
> do you mean if paramiko can see the Hostname in .ssh/config, they can login to aries without SSH_USER env variable?

yes

**Comment by garaemon** [comment]
> If they edit the src/jsk_data/*.py, they should want to try $ jsk_data, but they cannot without catkin bt in each time after editing it.

I think user run `catkin build` once and no need to re-run catkin to test it

**Comment by wkentaro** [comment]
> I think user run catkin build once and no need to re-run catkin to test it

I didn't see that. there was only __init__.py file under ros/deve/lib/python2.7.
so you're right, I will remove jsk_data_r. thanks.

**Comment by wkentaro** [comment]
paramiko can parse .ssh/config so maybe possible.

**Comment by garaemon** [comment]
I believe catkin build just creates `__init__.py` to append PYTHONPATH.

**Comment by wkentaro** [comment]
I
* removed jsk_data_r
* add feature to get config from `.ssh/config`.

**Comment by wkentaro** [comment]
> I believe catkin build just creates __init__.py to append PYTHONPATH.

Yeah, I mean that by:

>I didn't see that. there was only __init__.py file under ros/deve/lib/python2.7.
so you're right, I will remove jsk_data_r. thanks.

**Comment by garaemon** [comment]
LGTM, Can you squash commits? commit history is a little bit longer.

**Comment by wkentaro** [comment]
I squashed.

**Comment by wkentaro** [comment]
large/smallの
データを
privateへ
移動させました。

**Pull request merged**
