### PR TITLE
[jsk_topic_tools] add topic_statistics.py

### PR DESCRIPTION
**Pull request by furushchev**
utility script for measurement of data sizes

usage:

```
./topic_statistics.py                          ⮂  
Usage: topic_statistics.py [options] topic_name

Options:
  -h, --help      show this help message and exit
  -w WINDOW_SIZE  
  -d DURATION
```

e.g.

```
$ ./topic_statistics.py -w 50 wide_stereo/left/image_rect
start subscribing wide_stereo/left/image_rect
waiting for 50 msgs...
received 51 messages for 2.027576924 [sec]
size amount:	15670.617 [kB]
size avg:	307.267 [kB/msg]
```

```
$ ./topic_statistics.py -d 10 wide_stereo/left/image_rect
start subscribing wide_stereo/left/image_rect
waiting for 10 [sec]...
received 280 messages for 10.014266968 [sec]
size amount:	86034.76 [kB]
size avg:	307.267 [kB/msg]
rate:		8591.21893544 [kB/sec]
```

### CODE REVIEW

**Comment by furushchev** [comment]
test failed on indigo

```
rostest log file is in /workspace/jsk-ros-pkg/jsk_common/log/rostest-edb1a0e795aa-8314.log


-- run_tests.py: verify result "/workspace/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_topic_buffer_fixed_rate_and_update_rate.xml"


Built target _run_tests_jsk_topic_tools_rostest_test_test_topic_buffer_fixed_rate_and_update_rate.test


testhztest_chatter ... FAILURE!


FAILURE: test [hztest_chatter] did not generate test results


  File "/usr/lib/python2.7/unittest/case.py", line 331, in run


    testMethod()


  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 164, in fn


    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)


  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue


    raise self.failureException(msg)


--------------------------------------------------------------------------------


testhztest_chatter_buffer ... ok


testhztest_chatter_update ... ok


[ROSTEST]-----------------------------------------------------------------------





[jsk_topic_tools.rosunit-hztest_chatter_update/test_hz][passed]


[testhztest_chatter][failed]





SUMMARY


 * RESULT: FAIL


 * TESTS: 1


 * ERRORS: 0


 * FAILURES: 1





ERROR: The following tests failed to run:


 * testhztest_chatter
```

**Comment by furushchev** [comment]
failed again with same error.
Seems error is in hz_measure.
@garaemon How do you know about it?

**Comment by wkentaro** [comment]
@furushchev 

You should try running travis test with this commit to see the test output verbosely.
https://github.com/jsk-ros-pkg/jsk_travis/commit/d5d1c79e1dd0ad280a6f2ff205ee5bf323409a8d

**Comment by furushchev** [comment]
now travis passed. please merge if there is no problem

**Pull request merged**
