### PR TITLE
[jsk_topic_tools] Add documentation about color_utils.h

### PR DESCRIPTION
**Pull request by garaemon**
I don't know we should use doxygen or manually written markdown.

### CODE REVIEW

**Comment by garaemon** [comment]
we should use doxygen difinitely about this kind of documentation

**Comment by garaemon** [comment]
[here is document](http://docs.ros.org/api/jsk_topic_tools/html/)

**Comment by garaemon** [comment]
generate doxygen
```sh
$ rosdoc_lite `rospack find jsk_topic_tools` -o doc
```

**Comment by garaemon** [comment]
Updated to use doxygen

**Comment by garaemon** [comment]
In order to update docs.ros.org, we need to release new tag?

**Comment by garaemon** [comment]
```
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/825fae71ab9ea366e0b22e8dbe1e2948232cb2e8.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/81e56836490151bf3e2bf2b6790848a29cb90f6b.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/7cfbeed211a3f9a6507c86cebaeedb3e3c4387f8.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/b67f64890f6d5269c51a68744711f115a8f207ae.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/a4b3c8956ab7a3e6d293ba33b57fac42799e69e6.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/527c2c7f325707565a37b6289b3ee7eec5a0ab0b.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/438a85d0c4400de8ca8f108d20ec905de5df6a19.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/b4931581ca7c5741f7ee4ac9767a1174838296f7.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/592c4c18fd82522323a9f5646b8e648e18c9ef70.pickle': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.ros/rosdep/sources.cache/index': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/.config/catkin/verb_aliases/00-default-aliases.yaml': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/ros/ws_jsk_common/build/.catkin_tools.yaml': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/ros/ws_jsk_common/src/jsk_common': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/ros/ws_jsk_common/.catkin_tools/default/build.yaml': Permission denied
rm: cannot remove `/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_common-indigo-deb-true/workspace/build_tag/ros/ws_jsk_common/.catkin_tools/README': Permission denied
```

**Comment by 130s** [comment]
> In order to update docs.ros.org, we need to release new tag?

AFAIK no. Doc generation job and package build job on ros buildfarm should not be related (sorry if I'm wrong).

**Comment by garaemon** [comment]
Thanks!

◉  ryohei

**Comment by garaemon** [comment]
Document is not updated yet .... http://docs.ros.org/api/jsk_topic_tools/html/

**Comment by garaemon** [comment]
Document is not available because jsk_common is failing on devel jenkins.

http://jenkins.ros.org/job/devel-indigo-jsk_common/

**Comment by garaemon** [comment]
because of [this issue](https://github.com/jsk-ros-pkg/jsk_common/issues/742)

**Comment by garaemon** [comment]
```
E: Unable to locate package percol
```

http://jenkins.ros.org/view/Hdoc/job/doc-hydro-jsk_common/107/console

**Comment by garaemon** [comment]
https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L802

percol is specified as pip package

**Comment by garaemon** [comment]
https://github.com/ros/rosdistro/pull/7074#issuecomment-72710751

I found this feedback

**Comment by garaemon** [comment]
Hmm, is it too difficult to use doc.ros.org? Another option is to use gh-pages and automatically generate it in travis-ci

**Comment by k-okada** [comment]
I think we should point to release repo for doc entry of rosdistro

--
◉ Kei Okada

2015/02/13 13:52、Ryohei Ueda <notifications@github.com> のメッセージ:

**Comment by garaemon** [comment]
So do you mean remove jsk_tools from this file? https://github.com/ros/rosdistro/blob/master/hydro/distribution.yaml#L3012

**Comment by garaemon** [comment]
Or this file?
https://github.com/tork-a/jsk_common-release/blob/master/indigo.ignored

**Comment by garaemon** [comment]
Discussed with @k-okada offline and updating script of jenkins.ros.org to ignore pip packages is the best solution...

**Comment by k-okada** [comment]
ok, done -> https://github.com/ros-infrastructure/jenkins_scripts/pull/77

--
◉ Kei Okada

**Pull request merged**
