### PR TITLE
[jsk_tools] Copy rviz display to duplicate same config

### PR DESCRIPTION
**Pull request by wkentaro**
Added:
  - jsk_tools/bin/copy_rviz_display.py

### CODE REVIEW

**Comment by wkentaro** [comment]
```

[jsk_tilt_laser] /workspace/ros/ws_jsk_common/src/jsk_common/jsk_tilt_laser/src/spin_laser_snapshotter.cpp:36:21: fatal error: ros/ros.h: No such file or directory 

[jsk_tilt_laser]  #include                                           

[jsk_tilt_laser]                      ^                                         

[jsk_tilt_laser] compilation terminated.                                        

[jsk_tools] -- Detecting CXX compiler ABI info - done                           

[jsk_tilt_laser] make[2]: *** [CMakeFiles/spin_laser_snapshotter.dir/src/spin_laser_snapshotter.cpp.o] Error 1 

[jsk_tilt_laser] make[1]: *** [CMakeFiles/spin_laser_snapshotter.dir/all] Error 2 

[jsk_tilt_laser] make[1]: *** Waiting for unfinished jobs....     
```

**Comment by k-okada** [comment]
this is interesting,
you need to use `catkin_INCLUDE_DIR`
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tilt_laser/CMakeLists.txt#L21

I'm start seing this very recently, something has changed in catkin?
https://github.com/code-iai/snap_map_icp/pull/6

--
◉ Kei Okada

**Comment by snozawa** [comment]
I saw similar bug on other travis:
https://github.com/jsk-ros-pkg/jsk_control/pull/560
In the above PR's case, ros-$ROS_DISTRO-roscpp is installed, but cannot be included from the program.

**Comment by wkentaro** [comment]
Thanks for your comments, @k-okada @snozawa .
I'm trying to fix this at #1353

**Comment by wkentaro** [comment]
Sent PR to upstream: https://github.com/ros-visualization/rviz/pull/977

**Pull request closed without merging**
