### PR TITLE
[jsk.rosinstall] Add wstool_catkin for completion for wstool

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
do they have deb package? or does this going to be integrated with catkin 
package?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
there is no deb package.
this is just package for shell completion for user who uses wstool and ROS.
and it's maintained by the owner of https://github.com/vcstools/wstool.

**Comment by wkentaro** [comment]
wstool_catkin

**Comment by k-okada** [comment]
please ask him if he have plan to integrate this env hook to original
wstool package.
I'm afraid this will happen in very soon and when that happens, someone
might get into trouble with this source install.
remember that not everyone is capable of solving software issues by
themself, for example
https://github.com/jsk-ros-pkg/jsk_travis/commit/27b2b4137843f7f34761b2c171dedf6c118eda8f
cause trouble and I'm afraid 90% of students could not solve this.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Yeah, I'm asking.

I see.
I thought this package was useful for all students, however if there are
some probabilities of problems, should I only share this kind of pkg for
lab members and not add to rosinstall?

2015年6月20日土曜日、Kei Okada<notifications@github.com>さんは書きました:

> please ask him if he have plan to integrate this env hook to original
> wstool package.
> I'm afraid this will happen in very soon and when that happens, someone
> might get into trouble with this source install.
> remember that not everyone is capable of solving software issues by
> themself, for example
>
> https://github.com/jsk-ros-pkg/jsk_travis/commit/27b2b4137843f7f34761b2c171dedf6c118eda8f
> cause trouble and I'm afraid 90% of students could not solve this.
>
> --
> ◉ Kei Okada
>
>
> On Fri, Jun 19, 2015 at 11:41 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > there is no deb package.
> > this is just package for shell completion for user who uses wstool and
> ROS.
> > and it's maintained by the owner of https://github.com/vcstools/wstool.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/pull/1007#issuecomment-113534027
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1007#issuecomment-113695177>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by garaemon** [comment]
wstool env-hooks set ROS_WORKSPACE the end of ROS_PACKAGE_PATH. is it correct?

**Comment by garaemon** [comment]
In my environment, `roscd` leads me to `atlas_moveit_config`

**Comment by wkentaro** [comment]
I think that's only for `zsh`
You can remove that line of 
```
@[if DEVELSPACE]@
_SPACES=(`echo $ROS_PACKAGE_PATH | tr ':' ' '`)
export ROS_WORKSPACE=${_SPACES[0]}
unset _SPACES
@[else]@
unset ROS_WORKSPACE
@[end if]@
```
from wstool.bash.em.

I will send PR to wstool_catkin repo.

**Comment by wkentaro** [comment]
If you using `zsh` on `hydro`, this PR is necessary I think.
https://github.com/tkruse/wstool_catkin/pull/1

**Pull request merged**
