### PR TITLE
[jsk_data][download_data] support custom download dir / chmod

### LINKED ISSUE #1529: Sharing cached downloaded data
Some packages downloads rosbag or pretrained data on build time and they are cached at `~/.ros/data`.
Currently after building `jsk_recognition` packages, `~/.ros/data` uses disk space about 16GB.
For those who use mobile robots, it will be required to install each workspace on user spaces, which means that at least 16GB free space is required for each users.

### PR DESCRIPTION
**Pull request by furushchev**
This PR enables to optionally share the directory for cached downloaded data among users by setting environment variable `JSK_DATA_CACHE_DIR`.
This will close #1529.

- support custom cache directory for downloading data
  1. use environment variable `JSK_DATA_CACHE_DIR` if defined 
  2. use `ROS_HOME/data` if `ROS_HOME` is defined
  3. use `~/.ros/data`

- chmod cache dir to allow writing by other users on a computer

### CODE REVIEW

**Comment by furushchev** [comment]
Thank you!

**Comment by furushchev** [comment]
@k-okada Please release new version including this change when you have time :+1:

**Comment by k-okada** [comment]
done https://github.com/ros/rosdistro/pull/15277

--
◉ Kei Okada


2017-06-19 17:24 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Thanks a lot!!

**Pull request merged**
