### PR TITLE
install node_scripts in jsk_data

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by wkentaro** [comment]
@k-okada Maybe he wants you to merge and release this soon.

**Comment by k-okada** [comment]
ok, please help me to build test before merging https://github.com/jsk-ros-pkg/jsk_common/pull/1598

It seems `node_scripts` hasnot  been install for a long time, but I also worried about people moving directory names  (https://github.com/jsk-ros-pkg/jsk_recognition/pull/2305, https://github.com/jsk-ros-pkg/jsk_recognition/pull/2204#discussion_r143330375, https://github.com/PR2/app_manager/pull/6#issuecomment-411730685) 
If `roslaunch-check` works on `installed` directory, then it would be great.

**Comment by wkentaro** [comment]
Ok, please leave it to me.

**Comment by wkentaro** [comment]
I created PR: https://github.com/jsk-ros-pkg/jsk_common/pull/1599
Could you review it? @knorth55

**Pull request closed without merging**
