### PR TITLE
Run push build only on the master branch

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/jsk-ros-pkg/jsk_common/pull/1549#issuecomment-323616018

Close https://github.com/jsk-ros-pkg/jsk_common/pull/1551

### CODE REVIEW

**Comment by wkentaro** [comment]
@k-okada You can see there is only a single build of Travis CI.

**Comment by k-okada** [comment]
I'm afraid this will not run travis on PRs from other repository.

**Comment by wkentaro** [comment]
You're right. I will check that. 

BTW, do u know why it fails bacause of timeout when I create branch on the origin?

**Comment by wkentaro** [comment]
I confirmed that the PR build is triggered https://github.com/jsk-ros-pkg/jsk_common/pull/1551

**Comment by k-okada** [comment]
https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/266690515

```
import pkg_resources._vendor.packaging._compat # precompiled from
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/_compat.pyc
#
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/requirements.pyc
matches
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/requirements.py
import pkg_resources._vendor.packaging.requirements # precompiled from
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/requirements.pyc
#
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/pyparsing.pyc
matches
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/pyparsing.py
import pkg_resources._vendor.pyparsing # precompiled from
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/pyparsing.pyc
# /usr/lib/python2.7/weakref.pyc matches /usr/lib/python2.7/weakref.py
import weakref # precompiled from /usr/lib/python2.7/weakref.pyc
# /usr/lib/python2.7/copy.pyc matches /usr/lib/python2.7/copy.py
import copy # precompiled from /usr/lib/python2.7/copy.pyc
# /usr/lib/python2.7/pprint.pyc matches /usr/lib/python2.7/pprint.py
import pprint # precompiled from /usr/lib/python2.7/pprint.pyc
# /usr/lib/python2.7/threading.pyc matches /usr/lib/python2.7/threading.py
import threading # precompiled from /usr/lib/python2.7/threading.pyc
#
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/markers.pyc
matches
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/markers.py
import pkg_resources._vendor.packaging.markers # precompiled from
/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/markers.pyc
No output has been received in the last 10m0s, this potentially indicates a
stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on:
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

```

I think this something similar to the problem reported at
https://blog.sqreen.io/freeze-python-str-encode-threads/

--
◉ Kei Okada


2017-08-21 23:36 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
That's interesting. Thank you.
But I want to know why this problem arises recently at first.

**Comment by k-okada** [comment]
> But I want to know why this problem arises recently at first.

Agreed, I think some of PR pushed to master banch has merged, without checking the situation where someone created PR from their forked repository, or some of pip package has been updated. I think you're expert on both cases.

c.f. https://github.com/jsk-ros-pkg/jsk_common/issues/1562

**Comment by furushchev** [comment]
@wkentaro Please resolve conflicts

**Comment by wkentaro** [comment]
Rebased.

**Comment by k-okada** [comment]
it seems travis running ok for recent PR's https://github.com/jsk-ros-pkg/jsk_common/pull/1573
so we do not need this at this moment

**Comment by wkentaro** [comment]
Testing push build is just a duplicate and not required, so I think it is better that we avoid that.
It causes many job queues on Travis, and our GitHub flow will be made slow down.

**Comment by wkentaro** [comment]
@k-okada Could you please merge this?

**Comment by furushchev** [comment]
@k-okada ping

**Comment by k-okada** [comment]
I think we no longer need this. Not sure why, ...

screenshot from 2018-01-09 20-59-47

**Comment by wkentaro** [comment]
@k-okada I think it is because he sends the PR from his forked repository.

**Comment by k-okada** [comment]
I prefer everyone send  PR from forked repository .

--
◉ Kei Okada


2018-01-09 23:03 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
> I prefer everyone send  PR from forked repository .

So this PR is not necessary for now.

**Pull request closed without merging**
