### PR TITLE
[jsk_data][pr2_play.sh] support other rosbag arguments

### PR DESCRIPTION
**Pull request by furushchev**
e.g.

```bash
rosrun jsk_data pr2_play.sh data.bag -l --pause
```

### CODE REVIEW

**Comment by k-okada** [comment]
https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/238639196

```
+ catkin_test_results --verbose --all build
Skipping "catkin_tools_prebuild/package.xml": 'tests'
Full test results for 'jsk_data/test_results/jsk_data/roslaunch-check_launch_pr2_play.launch.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="roslaunch-check_launch_pr2_play.launch.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
  <failure message="roslaunch check [/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/launch/pr2_play.launch] failed" type=""/>
  </testcase>
  <system-out><![CDATA[[
[/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/launch/pr2_play.launch]:
	Missing package dependencies: jsk_data/package.xml: tf2_ros
]]></system-out>
</testsuite>
```

**Comment by furushchev** [comment]
@k-okada Thank you! Fixed!!

**Comment by k-okada** [comment]
failing on hydro https://travis-ci.org/jsk-ros-pkg/jsk_common/builds/242412246 

```
Skipping "assimp_devel/build/assimp-3.1.1/contrib/cppunit-1.12.1/contrib/xml-xsl/tests.xml": 'tests'
Full test results for 'jsk_data/test_results/jsk_data/roslaunch-check_launch_pr2_play.launch.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="roslaunch-check_launch_pr2_play.launch.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
  <failure message="roslaunch check [/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/launch/pr2_play.launch] failed" type=""/>
  </testcase>
  <system-out><![CDATA[[
[/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/launch/pr2_play.launch]:
	ROSLaunch config error: [/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/launch/pr2_play.launch] unknown <arg> attribute 'doc'
]]></system-out>
</testsuite>
-------------------------------------------------
Skipping "collada_urdf_jsk_patch/build/robot_model/src/collada_urdf/packa
```

**Comment by furushchev** [comment]
@k-okada Too strict linting!, but ok, fixed not to use `doc` attr and use comment instead.

**Pull request merged**
