### PR TITLE
[jsk_topic_tools] Add tool to check synchronized topics

### PR DESCRIPTION
**Pull request by wkentaro**
Added:
  - jsk_topic_tools/scripts/is_synchronized.py

cc: @otsubo

### CODE REVIEW

**Comment by wkentaro** [comment]
Could anyone review and merge this please?

**Comment by k-okada** [comment]
@otsubo did this work for you?

--
◉ Kei Okada

**Comment by k-okada** [comment]
@wkentaro, are you sure to update .travis

--
◉ Kei Okada

**Comment by wkentaro** [comment]
> @otsubo did this work for you?

I added him as cc for his info. I also use this.

> @wkentaro, are you sure to update .travis

the upgrading is needed because this pr is needed to make test pass.
https://github.com/jsk-ros-pkg/jsk_travis/commit/450c62ebdc454ee2b687076d91b9fc0beafdbbbb

**Comment by wkentaro** [comment]
otherwise, fails like https://github.com/jsk-ros-pkg/jsk_common/pull/1318, https://github.com/jsk-ros-pkg/jsk_common/pull/1316

**Comment by wkentaro** [comment]
should I upgrade jsk_travis to 0.2.4?

**Comment by wkentaro** [comment]
Could you please review and merge this?

**Pull request merged**
