### PR TITLE
[jsk_topic_tools] Republish after approximate synchronization

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
do we need to update documentation?

**Comment by wkentaro** [comment]
I added a doc.

**Comment by k-okada** [comment]
This still creating http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/-a-c-d-deb-e-C-CE-A-a-bef-e-c-e-c-3-ba-/

**Comment by wkentaro** [comment]
It will be fixed via https://github.com/jsk-ros-pkg/jsk_common/pull/1449.

**Pull request merged**
