### PR TITLE
[jsk_data] add wait_timer for timer method

### PR DESCRIPTION
**Pull request by shmpwk**
As to data_collection_server, wait_service_request for request method was implemented by https://github.com/jsk-ros-pkg/jsk_common/pull/1669 . 
So I apply it to the other methods such as timer method and all method.

### CODE REVIEW

**Comment by knorth55** [comment]
I think `waiting` for `all` method is meaningless because all `msgs` are arrived and updated in `sync_sub_and_save_cb`.
but for `timer`, it might be useful.

**Comment by knorth55** [comment]
@shmpwk can you check https://github.com/shmpwk/jsk_common/pull/1 ?

**Comment by shmpwk** [comment]
@knorth55 You're right. I just tried it for `timer` and thought that it can be also applied to `all`.

**Comment by shmpwk** [comment]
Thank you for the revise.
I fix typo on https://github.com/shmpwk/jsk_common/pull/1 by https://github.com/jsk-ros-pkg/jsk_common/pull/1697/commits/fac3f9c863f7298ff47868c3fee27010d8b7d03f. 
I confirm it works with `wait_save_request`: `true` or `false` and `wait_timer`: `true` or `false`.

**Review by knorth55 — APPROVED** [review]

**Pull request merged**
