### PR TITLE
[jsk_topic_tools] Find Boost_LIBRARIES once nodelt.cmake

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
oops, roslint need to be build_depend.

**Comment by wkentaro** [comment]
no, rosdep fails that is the cause.

```
+ '[' -e '/workspace/jsk-ros-pkg/jsk_common/.travis/rosdep-install.sh]'

/bin/bash: line 75: [: missing `]'

+ wget http://raw.github.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh -O -

+ bash

--2015-12-07 11:44:56--  http://raw.github.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh

Resolving raw.github.com (raw.github.com)... 103.245.222.133

Connecting to raw.github.com (raw.github.com)|103.245.222.133|:80... connected.

HTTP request sent, awaiting response... 301 Moved Permanently

Location: https://raw.github.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh [following]

--2015-12-07 11:44:56--  https://raw.github.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh

Connecting to raw.github.com (raw.github.com)|103.245.222.133|:443... connected.

HTTP request sent, awaiting response... 301 Moved Permanently

Location: https://raw.githubusercontent.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh [following]

--2015-12-07 11:44:57--  https://raw.githubusercontent.com/jsk-ros-pkg/jsk_travis/master/rosdep-install.sh

Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 103.245.222.133

Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|103.245.222.133|:443... connected.

HTTP request sent, awaiting response... 200 OK

Length: 648 [text/plain]

Saving to: 'STDOUT'




 0% [                                       ] 0           --.-K/s              
100%[======================================>] 648         --.-K/s   in 0s      



2015-12-07 11:44:58 (114 MB/s) - written to stdout [648/648]





ERROR: Rosdep experienced an internal error.

Please go to the rosdep page [1] and file a bug report with the message below.

[1] : http://www.ros.org/wiki/rosdep



rosdep version: 0.11.4



Bad installer [pip]: [Errno 2] No such file or directory



+ source /opt/ros/indigo/setup.bash
```

**Comment by garaemon** [comment]
strange error about boost_program_options
```
$ catkin b jsk_recognition_utils
==> Expanding alias 'bt' from 'catkin bt' to 'catkin b --this'
==> Expanding alias 'b' from 'catkin b --this' to 'catkin build --this'
------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/lueda/ros/hydro_parent/devel:/opt/ros/hydro
Workspace:                   /home/lueda/ros/hydro
Source Space:       [exists] /home/lueda/ros/hydro/src
Build Space:        [exists] /home/lueda/ros/hydro/build
Devel Space:        [exists] /home/lueda/ros/hydro/devel
Install Space:     [missing] /home/lueda/ros/hydro/install
DESTDIR:                     None
------------------------------------------------------------------------------
Isolate Develspaces:         False
Install Packages:            False
Isolate Installs:            False
------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------------------------
Found '335' packages in 0.5 seconds.
Starting ==> dynamic_tf_publisher
Starting ==> image_transport
Starting ==> jsk_recognition_msgs
Starting ==> pcl_conversions
Finished <== pcl_conversions       [ 0.2 seconds ]
Starting ==> pcl_ros
Finished <== image_transport       [ 0.5 seconds ]
Finished <== dynamic_tf_publisher  [ 0.6 seconds ]
Finished <== jsk_recognition_msgs  [ 0.7 seconds ]
Starting ==> jsk_topic_tools
Finished <== pcl_ros               [ 1.0 seconds ]

[jsk_topic_tools] ==> '/home/lueda/ros/hydro/build/jsk_topic_tools/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' in '/home/lueda/ros/hydro/build/jsk_topic_tools'
[ 11%] [ 22%] Built target jsk_topic_tools_generate_messages_py
Built target jsk_topic_tools_generate_messages_eus
[ 30%] Built target jsk_topic_tools_generate_messages_lisp
[ 38%] Built target jsk_topic_tools_generate_messages_cpp
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/hz_measure
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/deprecated_relay
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/block
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/passthrough
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/mux
[ 40%] Built target standalone_complexed_nodelet
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/snapshot
[ 42%] Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/lightweight_throttle
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/relay
Built target transform_merger
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/string_relay
[ 42%] Built target jsk_topic_tools_gencpp
Linking CXX executable /home/lueda/ros/hydro/devel/lib/jsk_topic_tools/vital_checker
[ 42%] Built target jsk_topic_tools_generate_messages
[ 44%] Built target topic_buffer_client
[ 45%] Built target topic_buffer_server
[ 47%] Built target static_transform_pose_stamped
[ 83%] Built target jsk_topic_tools
/usr/bin/ld: CMakeFiles/hz_measure.dir/hz_measure.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is defined in DSO /usr/lib/libboost_program_options.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_program_options.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
/usr/bin/ld: CMakeFiles/deprecated_relay.dir/deprecated_relay.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is defined in DSO /usr/lib/libboost_program_options.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_program_options.so.1.46.1: could not read symbols: Invalid operationmake[2]:
collect2: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/hz_measure] Error 1
ld returned 1 exit status
make[1]: *** [CMakeFiles/hz_measure.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/deprecated_relay] Error 1
make[1]: *** [CMakeFiles/deprecated_relay.dir/all] Error 2
/usr/bin/ld: CMakeFiles/relay.dir/relay.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is defined in DSO /usr/lib/libboost_program_options.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_program_options.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
//usrusr/bin/ld: CMakeFiles//mux.dirbin//mux.cpp.old::  CMakeFilesundefined /passthrough.dirreference /passthrough.cpp.oto : symbol undefined 'reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/boost::program_options::options_description_easy_init::operator()(char const*, char const*)bin/ld'
: /usrnote:/bin '/ldboost::program_options::options_description_easy_init::operator()(char const*, char const*): ' note:is  'defined boost::program_options::options_description_easy_init::operator()(char const*, char const*)in ' DSOis  /defined usr/in lib/DSO libboost_program_options.so.1.46.1/usr so/lib try/libboost_program_options.so.1.46.1 adding so it try to adding the it linker to command the line linker
/ commandusr/ linelib/
/libboost_program_options.so.1.46.1usr/: libcould/libboost_program_options.so.1.46.1 not:  readcould  symbolsnot : readInvalid symbols operation:
Invalid operation
collect2: collect2: ld returned 1 exit status
ld returned 1 exit status
/usr/bin/ld: CMakeFiles/block.dir/block.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is defined in DSO /usr/lib/libboost_program_options.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_program_options.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/relay] Error 1
make[1]: *** [CMakeFiles/relay.dir/all] Error 2
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/passthrough] Error 1
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/mux] Error 1
make[1]: *** [CMakeFiles/passthrough.dir/all] Error 2
make[1]: *** [CMakeFiles/mux.dir/all] Error 2
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/block] Error 1
make[1]: *** [CMakeFiles/block.dir/all] Error 2
/usr/bin/ld: CMakeFiles/vital_checker.dir/vital_checker.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is defined in DSO /usr/lib/libboost_program_options.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_program_options.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/vital_checker] Error 1
make[1]: *** [CMakeFiles/vital_checker.dir/all] Error 2
/usr/bin/ld: CMakeFiles/lightweight_throttle.dir/lightweight_throttle.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is /defined in DSOusr //binusr/ld: /CMakeFiles/string_relay.dirlib//string_relay.cpp.olibboost_program_options.so.1.46.1: undefined so reference  to symboltry ' adding it boost::program_options::options_description_easy_init::operator()(char const*, char const*)'to
/usrthe /bin/linkerld:  note: command'boost::program_options::options_description_easy_init::operator()(char const*, char const*) line' is
/ defined usrin DSO/lib /usr//lib/libboost_program_options.so.1.46.1libboost_program_options.so.1.46.1 so:  try couldadding it not to  the linkerread command  line
/symbolsusr/lib: /libboost_program_options.so.1.46.1Invalid: could operation not
read symbols: Invalid operation
collect2: collect2: ld returned 1 exit status
ld returned 1 exit status
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/string_relay] Error 1
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/lightweight_throttle] Error 1
make[1]: *** [CMakeFiles/string_relay.dir/all] Error 2
make[1]: *** [CMakeFiles/lightweight_throttle.dir/all] Error 2
/usr/bin/ld: CMakeFiles/snapshot.dir/snapshot.cpp.o: undefined reference to symbol 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/usr/bin/ld: note: 'boost::program_options::options_description_easy_init::operator()(char const*, char const*)' is defined in DSO /usr/lib/libboost_program_options.so.1.46.1 so try adding it to the linker command line
/usr/lib/libboost_program_options.so.1.46.1: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [/home/lueda/ros/hydro/devel/lib/jsk_topic_tools/snapshot] Error 1
make[1]: *** [CMakeFiles/snapshot.dir/all] Error 2
make: *** [all] Error 2
[jsk_topic_tools] <== '/home/lueda/ros/hydro/build/jsk_topic_tools/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j' failed with return code '2'
                                                                                                                                          
Failed   <== jsk_topic_tools       [ 1.6 seconds ]
[build] There were '1' errors:

Failed to build package 'jsk_topic_tools' because the following command:

# Command to reproduce:
cd /home/lueda/ros/hydro/build/jsk_topic_tools && /home/lueda/ros/hydro/build/jsk_topic_tools/build_env.sh /usr/bin/make --jobserver-fds=3,5 -j; cd -

# Path to log:
cat /home/lueda/ros/hydro/build/build_logs/jsk_topic_tools.log

Exited with return code: 2

[build] Runtime: 4.2 seconds

```

**Comment by garaemon** [comment]
Remove build directory solved the issue.

**Pull request merged**
