### PR TITLE
Correct a line mistaken, easy but critical

### PR DESCRIPTION
**Pull request by 7675t**
Sorry, my #1601 had an easy bug.

### CODE REVIEW

**Comment by 7675t** [comment]
Travis failed only in Melodic, roslaunch-check on jsk_data/pr2_play.launch

**Comment by k-okada** [comment]
```
                                                                                
[jsk_data:make] catkin_generated/env_cached.sh /usr/bin/python2 /opt/ros/melodic/share/catkin/cmake/test/run_tests.py /home/travis/ros/ws_jsk_common/build/jsk_data/test_results/jsk_data/roslaunch-check_launch_pr2_play.launch.xml "/usr/bin/cmake -E make_directory /home/travis/ros/ws_jsk_common/build/jsk_data/test_results/jsk_data" "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/travis/ros/ws_jsk_common/build/jsk_data/test_results/jsk_data/roslaunch-check_launch_pr2_play.launch.xml' '/home/travis/ros/ws_jsk_common/src/jsk_common/jsk_data/launch/pr2_play.launch' "




                                             
                                                                                
[jsk_data:make] [93mxacro.py is deprecated; please use xacro instead[0m




                                                                                
[jsk_data:make] Traceback (most recent call last):



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check", line 90, in <module>



                                                                                
[jsk_data:make]     error_msg = check_roslaunch_file(roslaunch_path, use_test_depends=options.test_depends)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/share/roslaunch/cmake/../scripts/roslaunch-check", line 47, in check_roslaunch_file



                                                                                
[jsk_data:make]     error_msg = roslaunch.rlutil.check_roslaunch(roslaunch_file, use_test_depends=use_test_depends)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/rlutil.py", line 193, in check_roslaunch



                                                                                
[jsk_data:make]     rl_config = roslaunch.config.load_config_default([f], DEFAULT_MASTER_PORT, verbose=False)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 457, in load_config_default




                                                                                
[jsk_data:make]     loader.load(f, config, argv=args, verbose=verbose)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 751, in load



                                                                                
[jsk_data:make]     self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 723, in _load_launch



                                                                                
[jsk_data:make]     self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 687, in _recurse_load




                                                                                
[jsk_data:make]     val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call



                                                                                
[jsk_data:make]     return f(*args, **kwds)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 591, in _include_tag




                                                                                
[jsk_data:make]     inc_filename = self.resolve_args(tag.attributes['file'].value, context)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 185, in resolve_args



                                                                                
[jsk_data:make]     return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 392, in resolve_args



                                                                                
[jsk_data:make]     resolved = _resolve_args(resolved, context, resolve_anon, commands)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 405, in _resolve_args




                                                                                
[jsk_data:make]     resolved = commands[command](resolved, a, args, context)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 166, in _find



                                                                                
[jsk_data:make]     source_path_to_packages=source_path_to_packages)



                                                                                
[jsk_data:make]   File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 212, in _find_executable



                                                                                
[jsk_data:make]     full_path = _get_executable_path(rp.get_path(args[0]), path)



                                                                                
[jsk_data:make]   File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path



                                                                                
[jsk_data:make]     raise ResourceNotFound(name, ros_paths=self._ros_paths)




                                                                                
[jsk_data:make] rospkg.common.ResourceNotFound: openni_launch
```
wait for https://github.com/ros-drivers/openni_camera/issues/68

**Comment by 7675t** [comment]
Thanks!

**Comment by 7675t** [comment]
Now it pass travis.

**Comment by k-okada** [comment]
When you introduced new bugs, please consider adding test code.
In general, testing GUI program is difficult, but I think just to check if we can start node without error, is very useful.
https://github.com/jsk-ros-pkg/jsk_common/pull/1603#issuecomment-421287938
https://github.com/k-okada/jsk_visualization/commit/b9bd8cb963a15225316d3ef4885787a375a84571

**Pull request merged**
