### PR TITLE
Fix data_collection_server

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
I rebase the commits to make test pass.

**Comment by wkentaro** [comment]
Rebased.

**Comment by wkentaro** [comment]
I'm not sure why, but it fails.. No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by k-okada** [comment]
moved to #1549

**Pull request closed without merging**
