### PR TITLE
[image_view2] Support OpenCV3

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
https://github.com/ros-perception/vision_opencv/blob/indigo/opencv_apps/src/nodelet/camshift_nodelet.cpp#L51

Seems including `opencv2/highgui/highgui.h` might work

**Comment by wkentaro** [comment]
Thanks, it worked.

**Comment by k-okada** [comment]
need rebase...

**Comment by wkentaro** [comment]
Rebased. And I added a test with opencv3.

**Pull request merged**
