### PR TITLE
Move jsk_tools documents to rtd

### LINKED ISSUE #1250: [Super Lower Priority] why rtd does not have documents of jsk_tools?
how can  I add https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tools/README.md to  https://jsk-common.readthedocs.org/en/latest/ ?

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #1250

### CODE REVIEW

**Comment by k-okada** [comment]
Hummm


Having document and source code should  in same directory may better

--
◉ Kei Okada

2015/11/29 14:49、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
soft link does not work?
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/doc

**Comment by wkentaro** [comment]
comments?

**Comment by wkentaro** [comment]
ping

**Comment by wkentaro** [comment]
@k-okada 
I tried to use softlink and now the diff is small.

**Pull request closed without merging**
