### PR TITLE
[jsk.rosinstall] Add jsk_common_msgs and jsk_3rdparty

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
According to https://github.com/jsk-ros-pkg/jsk_common/pull/988

**Comment by k-okada** [comment]
that is taken care at https://github.com/k-okada/jsk_common/commit/79ac469f3d94d4b1f06fb82e1ca50dc7ed9d60b3

**Comment by garaemon** [comment]
I see

**Comment by garaemon** [comment]
I cannot find jsk_common_msgs in http://www.ros.org/debbuild/hydro.html, is it ok?

**Comment by k-okada** [comment]
not yet released, please wait a moment.

**Comment by garaemon** [comment]
```bash
cd ~/ros/hydro/src
wstool merge jsk-ros-pkg/jsk.rosinstall
wstool update jsk-ros-pkg/jsk_common_msgs jsk-ros-pkg/jsk_3rdparty
```

**Comment by garaemon** [comment]
not yet released http://www.ros.org/debbuild/hydro.html
I'm afraid that you have not released it?

**Comment by k-okada** [comment]
Please wait few more days... I'm super busy now...

--
◉ Kei Okada

2015/06/18 1:39、Ryohei Ueda <notifications@github.com> のメッセージ:

**Comment by k-okada** [comment]
done, releasing will take 2-3 days to compile all of jsk sources with 2 distro

**Comment by garaemon** [comment]
thanks!

**Pull request closed without merging**
