### PR TITLE
[WIP] TEST COMMIT: test for roslint report

### PR DESCRIPTION
**Pull request by wkentaro**
Need https://github.com/jsk-ros-pkg/jsk_travis/pull/219

    Modified:
     jsk_topic_tools/src/hz_measure_nodelet.cpp

### CODE REVIEW

**Comment by wkentaro** [comment]
```
Set cache size limit to 20.0 Gbytes
+ echo 'Acquire::http {proxy "http://172.17.42.1:3142"; };'
+ apt-get update -qq
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/trusty/Release.gpg  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/restricted/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/restricted/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/restricted/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/main/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/restricted/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/source/Sources  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/main/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/restricted/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/universe/binary-amd64/Packages  Unable to connect to 172.17.42.1:3142:
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by garaemon** [comment]
wow url has been changed

```
lueda@jenkins:~$ ifconfig docker0
docker0   Link encap:Ethernet  HWaddr 02:42:8a:16:48:67  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:8aff:fe16:4867/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:73878 errors:0 dropped:0 overruns:0 frame:0
          TX packets:111960 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4662012 (4.6 MB)  TX bytes:654422920 (654.4 MB)
```

**Comment by garaemon** [comment]
@k-okada Can you set static IP for docker host?

**Comment by garaemon** [comment]
I will fix the issue.

**Comment by garaemon** [comment]
URL issue has been fixed

**Comment by wkentaro** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/97650149/log.txt
```
Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/packages.ros.org_ros-shadow-fixed_ubuntu_dists_trusty_InReleaseW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.ros.org trusty InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)



E: Couldn't create temporary file to work with /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_Release - mkstemp (28: No space left on device)

+ echo Ignore error of apt-get update

Ignore error of apt-get update

+ apt-get install -qq -y git wget sudo lsb-release ccache apt-cacher-ng

E: Couldn't create temporary file to work with /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_Release - mkstemp (28: No space left on device)

E: The package lists or status file could not be parsed or opened.

++ exit 1
```

**Comment by wkentaro** [comment]
I'm restarting

**Comment by wkentaro** [comment]
restart does not work

```
travis_time_end
Error response from daemon: database or disk is full
+ pwd
/var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk
```

**Comment by wkentaro** [comment]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/97650149/log.txt

**Comment by wkentaro** [comment]
@furushchev 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/97827186/log.txt
```
+ '[' 1312 '!=' false ']'

+ ROSLINT_RESULT_PATH=/tmp/roslint_result.xml

+ cd /workspace/jsk-ros-pkg/jsk_common

+ .travis/get_roslint_result_xml.py --repo-slug jsk-ros-pkg/jsk_common --pr-number 1312 --out-file /tmp/roslint_result.xml

+ '[' -e /tmp/roslint_result.xml ']'

+ cd /workspace/jsk-ros-pkg/jsk_common

+ .travis/comment_roslint_result.py -i /tmp/roslint_result.xml -t

usage: comment_roslint_result.py [-h] -i INPUT_PATH [-c CACHE_DIR] -t TOKEN

comment_roslint_result.py: error: argument -t: expected one argument
```

**Comment by furushchev** [comment]
@wkentaro Need to let travis know github token via environment variable `GH_TOKEN` to comment.

**Comment by wkentaro** [comment]
@k-okada Could you please add `GH_TOKEN` as environmental variable for GitHub Token?

**Comment by wkentaro** [comment]
@k-okada Could you please add GH_TOKEN as environmental variable for GitHub Token?

**Comment by k-okada** [comment]
please source ~/.token

--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada Am I missing something?
```

+ ROSLINT_RESULT_PATH=/tmp/roslint_result.xml

+ cd /workspace/jsk-ros-pkg/jsk_common

+ .travis/get_roslint_result_xml.py --repo-slug jsk-ros-pkg/jsk_common --pr-number 1312 --out-file /tmp/roslint_result.xml

+ '[' -e /tmp/roslint_result.xml ']'

+ source /workspace/.token

/bin/bash: line 226: /workspace/.token: No such file or directory

++ error

++ travis_time_end 31
```

**Comment by wkentaro** [comment]
I did `source $HOME/.token`.

**Comment by wkentaro** [comment]
still fails

```
+ '[' indigo == hydro ']'
+ '[' 1312 '!=' false ']'
+ ROSLINT_RESULT_PATH=/tmp/roslint_result.xml
+ cd /workspace/jsk-ros-pkg/jsk_common
+ .travis/get_roslint_result_xml.py --repo-slug jsk-ros-pkg/jsk_common --pr-number 1312 --out-file /tmp/roslint_result.xml
+ '[' -e /tmp/roslint_result.xml ']'
+ source /.token
/bin/bash: line 226: /.token: No such file or directory
+ echo 'GitHub Token not found. skipping'
GitHub Token not found. skipping
```

**Comment by wkentaro** [comment]
```
sending request to https://api.github.com/repos/jsk-ros-pkg/jsk_common/pulls/1312/comments

received response [401] Bad credentials
```

@k-okada Could you please update the access right of the token?

**Comment by k-okada** [comment]
I have added GITHUB_ACCCESS_TOKEN environment variables, but I'm afraid this only works for jks-ros-pkg repository, not work for forked repository.

**Comment by wkentaro** [comment]
Maybe this is impossible because of the way to access the GITHUB token. so I'm closing this.

**Pull request closed without merging**
