### PR TITLE
Resolve dependency on python-gdown with rosdep

### PR DESCRIPTION
**Pull request by h-kamada**

### CODE REVIEW

**Comment by k-okada** [comment]
which script need this?

**Comment by wkentaro** [comment]
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_data/src/jsk_data/download_data.py#L81

**Comment by k-okada** [comment]
if you add new dependency, please check if that is released on fedra/debian -> https://github.com/ros/rosdistro/pull/13397

**Comment by wkentaro** [comment]
I see.

BTW, is that impossible to stop releasing fedra/debian? (Do we need to support fedra/debian?)

**Comment by k-okada** [comment]
> BTW, is that impossible to stop releasing fedra/debian? (Do we need to
support fedra/debian?)

no, that's defined in build.ros.org

--
◉ Kei Okada


2016-12-13 15:40 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Pull request merged**
