### PR TITLE
[WIP] [jsk_tools] Simplify test_topic_published.py for testing on travis

### LINKED ISSUE #1403: [jsk_tools] test_topic_published.py won't work on Travis?
Maybe it does not work on Travis.
https://github.com/start-jsk/jsk_apc/pull/1620#issuecomment-223271982

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #1403

### CODE REVIEW

**Comment by wkentaro** [comment]
Validated in https://github.com/start-jsk/jsk_apc/pull/1634

**Comment by k-okada** [comment]
what was the problem

2016年6月6日月曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Validated in start-jsk/jsk_apc#1634
> <https://github.com/start-jsk/jsk_apc/pull/1634>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1404#issuecomment-223895556>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3A8QuviXMUgR8tZ6MFx5Tjd1a3Lxks5qI9ffgaJpZM4IupRw>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Actually, I don't know much about the stability of `jsk_tools.sanity_lib`, and what was the problem.
The test with `test_topic_published.py`. that is using `jsk_tools.sanity_lib` inside, fails only on Travis.
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tools/src/jsk_tools/sanity_lib.py#L49

**Comment by wkentaro** [comment]
Should I change the `jsk_tools.sanity_lib`?

**Pull request closed without merging**
