### PR TITLE
[.travis.yml] Add test for jade

### PR DESCRIPTION
**Pull request by wkentaro**
**PLEASE DON'T MERGE THIS NOW**

ros-jade-pr2eus has not yet released.
Is these EXTRA_DEB necessary for all ROS versions of this pkg? @k-okada @garaemon

### CODE REVIEW

**Comment by wkentaro** [comment]
Please wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/102 to be merged
and submodules to be updated.

**Comment by k-okada** [comment]
If I undestand correctly, pr2eus is used in test code and we do not want to
depend jsk_common to pr2eus so install the as an extra deb

2015年6月18日木曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Please wait for jsk-ros-pkg/jsk_travis#102
> <https://github.com/jsk-ros-pkg/jsk_travis/pull/102> to be merged
> and submodules to be updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1003#issuecomment-112872442>
> .
>


-- 
--
◉ Kei Okada

**Comment by garaemon** [comment]
Yes, Correct

2015年6月19日金曜日、Kei Okada<notifications@github.com>さんは書きました:

> If I undestand correctly, pr2eus is used in test code and we do not want to
> depend jsk_common to pr2eus so install the as an extra deb
>
> 2015年6月18日木曜日、Kentaro Wada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
> > Please wait for jsk-ros-pkg/jsk_travis#102
> > <https://github.com/jsk-ros-pkg/jsk_travis/pull/102> to be merged
> > and submodules to be updated.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/pull/1003#issuecomment-112872442
> >
> > .
> >
>
>
> --
> --
> ◉ Kei Okada
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1003#issuecomment-113513802>
> .
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
I see.
Are you planning to release pr2eus for jade soon? @k-okada 
Or should I change the test code to adapt for jade test. I mean change to install pr2eus from source if it's the test for jade.

**Comment by k-okada** [comment]
how about try  NOT_TEST_INSTALL="true", to avoid test code, until pr2eus is 
released.

--
◉ Kei Okada

**Comment by k-okada** [comment]
> how about try  NOT_TEST_INSTALL="true", to avoid test code, 

this is wrong

**Comment by k-okada** [comment]
create new PR for #1010

**Pull request closed without merging**
