### PR TITLE
[jsk_data] Add playback launch for kinect2 using kinect2_bridge

### PR DESCRIPTION
**Pull request by wkentaro**
The reason I'd like to put this at this package is
that installing kinect2_bridge package is not so easy.

### CODE REVIEW

**Comment by wkentaro** [comment]
cc @otsubo

**Comment by wkentaro** [comment]
also https://github.com/ros-perception/image_pipeline/pull/168 will support exact time sync as kinect2_bridge does.

**Comment by wkentaro** [comment]
Could someone review and merge this please?

**Comment by k-okada** [comment]
@otsubo did you use this?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
just for info I added him as cc, I'm using this.

**Comment by wkentaro** [comment]
Could you please review and merge this?

**Comment by garaemon** [comment]
LGTM, but we need patch for package.xml for the next release

**Pull request merged**
