### PR TITLE
Add warnNoRemap to ConnectionBasedNodelet

### PR DESCRIPTION
**Pull request by wkentaro**
Waiting for upstream:

- https://github.com/ros/nodelet_core/pull/61

### CODE REVIEW

**Comment by wkentaro** [comment]
https://github.com/ros/nodelet_core/pull/61 is merged and released to indigo.

**Comment by wkentaro** [comment]
Sorry, I have misunderstood.
According to http://repositories.ros.org/status_page/compare_indigo_jade_kinetic_lunar.html?q=nodelet, 1.9.11 is only released to lunar.

**Comment by furushchev** [comment]
@wkentaro Please resolve conflcts.

**Comment by wkentaro** [comment]
This requires nodelet 1.9.13 in indigo
So we should skip this for now.
https://github.com/ros/nodelet_core/pull/61#issuecomment-340241744

**Comment by wkentaro** [comment]
Rebased.

**Pull request merged**
