### PR TITLE
[jsk_tools/bin/battery_capacity_summary.py] print N/A for unavailable data

### PR DESCRIPTION
**Pull request by furushchev**
…

### CODE REVIEW

**Comment by furushchev** [comment]
```
[jsk_data] ERROR: Failure: ImportError (No module named freezegun)              

[jsk_data] ---------------------------------------------------------------------- 

[jsk_data] Traceback (most recent call last):                                   

[jsk_data]   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName 

[jsk_data]     addr.filename, addr.module)                                      

[jsk_data]   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath 

[jsk_data]     return self.importFromDir(dir_path, fqname)                      

[jsk_data]   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir 

[jsk_data]     mod = load_module(part_fqname, fh, filename, desc)               

[jsk_data]   File "/workspace/ros/ws_jsk_common/src/jsk_common/jsk_data/src/jsk_data/tests/test_util.py", line 6, in  

[jsk_data]     from freezegun import freeze_time                                

[jsk_data] ImportError: No module named freezegun                               
```

**Comment by garaemon** [comment]
https://travis-ci.org/jsk-ros-pkg/jsk_common/jobs/103787005#L1549

It should be installed...

**Comment by garaemon** [comment]
```
Detected a distutils installed project ('six') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
ERROR: the following rosdeps failed to install
  pip: command [sudo -H pip install -U percol] failed
  pip: Failed to detect successful installation of [percol]
  pip: command [sudo -H pip install -U slacker-cli] failed
  pip: Failed to detect successful installation of [slacker-cli]
  pip: command [sudo -H pip install -U pygithub3] failed
  pip: Failed to detect successful installation of [pygithub3]
  pip: command [sudo -H pip install -U freezegun] failed
  pip: Failed to detect successful installation of [freezegun]
```

**Comment by garaemon** [comment]
all the pip install has been failed. I restarted travis

**Comment by furushchev** [comment]
@garaemon Thanks for solving problem and merging! :+1:

**Pull request merged**
