### PR TITLE
[jsk_data] Remap /kinect_head topics to /kinect_head_c2 to play rosbag for pr2

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/jsk-ros-pkg/jsk_common/issues/1429

### CODE REVIEW

**Comment by k-okada** [comment]
please review @furushchev

**Comment by furushchev** [comment]
@k-okada I worked on this pr with @wkentaro, and LGTM.

**Comment by furushchev** [comment]
```bash
[dynamic_tf_publisher] -- catkin 0.6.11
[assimp_devel] -- catkin 0.6.11
[downward] -- catkin 0.6.11
[bayesian_belief_networks] -- catkin 0.6.11
[dynamic_tf_publisher] CMake Error at /opt/ros/hydro/share/catkin/cmake/catkin_add_env_hooks.cmake:91 (file):
[dynamic_tf_publisher]   file COPY cannot set modification time on
[dynamic_tf_publisher]   "/workspace/ros/ws_jsk_common/devel/etc/catkin/profile.d/05.catkin_make_isolated.bash"
[dynamic_tf_publisher] Call Stack (most recent call first):
[dynamic_tf_publisher]   /opt/ros/hydro/share/catkin/cmake/all.cmake:199 (catkin_add_env_hooks)
[dynamic_tf_publisher]   /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:20 (include)
[dynamic_tf_publisher]   CMakeLists.txt:4 (find_package)
[dynamic_tf_publisher] 
[dynamic_tf_publisher] 
```

**Comment by furushchev** [comment]
Now test passed
@k-okada Please merge if there is no problem.

**Pull request merged**
