### PR TITLE
call ros::param::get before set not to overwrite

### PR DESCRIPTION
**Pull request by furushchev**
For example, considering the parameter for `standalone_complexed_nodelet` like below:

```
   nodelets:
     -  name: node_name
        type: nodelet_type
        remappings:
          - from: from_topic
            to: to_topic
          - from: from_topic
            to: to_topic
        params:
          - name: approximate_sync
            value: true
          - name: queue_size
            value: 100
```

it sets parameters of names:

- node_name/approximate_sync: true
- node_name/queue_size: 100

which is expected behavior.
However, when setting these parameters, the existing parameters are cleared.

This PR fixes the behavior not to clear (but overwriting is allowed) any existing parameters.

### CODE REVIEW

**Comment by knorth55** [comment]
what do you mean by *the existing parameters*?
existing parameters is parameters for `node_name` but not `approximate_sync` such as `node_name/slop`?

**Comment by furushchev** [comment]
I mean parameters set before launching the standalone complexed node under the private namespace.
For example,

Given a standalone complexed node with parameters as follows:

```
<launch>
  <node name="manager" pkg="jsk_topic_tools" type="standalone_complexed_node">
    <rosparam>
   nodelets:
     -  name: node_name
        type: nodelet_type
        remappings:
          - from: from_topic
            to: to_topic
          - from: from_topic
            to: to_topic
        params:
          - name: approximate_sync
            value: true
          - name: queue_size
            value: 100
    </rosparam>
  </node>
  <rosparam>
    node_name/foo: bar
    node_name/baz: 0
    node_name/aaa/bbb: ccc
  </rosparam>
</launch>
```

I expect the parameters are set as follows:

```
/node_name/approximate_sync: true
/node_name/queue_size: 100
/node_name/foo: bar
/node_name/baz: 0
/node_name/aaa/bbb: ccc
```

But the actual parameters after launch the files are as follows:

```
/node_name/approximate_sync: true
/node_name/queue_size: 100
```

**Comment by k-okada** [comment]
thanks , can you create test code for this?
--
◉ Kei Okada



2019年12月2日(月) 9:28 Yuki Furuta <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Sure, added.

**Comment by furushchev** [comment]
`FAILURE: Test node [rostest/publishtest] does not exist or is not executable`

It seems `publishtest` is not released on indigo.

**Comment by k-okada** [comment]
run test >= kinetic
--
◉ Kei Okada



2019年12月3日(火) 9:30 Yuki Furuta <notifications@github.com>:

**Comment by furushchev** [comment]
I added test on kinetic/melodic on the latest commit.

**Comment by furushchev** [comment]
@k-okada kindly ping to maintainer :)

**Pull request merged**
