### PR TITLE
import roslib.message explicitly to suport python3

### PR DESCRIPTION
**Pull request by softyanija**
When I run original code in noetic, error "AttributeError: module 'roslib' has no attribute 'message'" occured. 
I fixed it to avoid this error .

### CODE REVIEW

**Comment by tkmtnt7000** [comment]
Same error occurs before noetic, but nice PR.
Maybe you should change the commit message.

```python
$ ipython
impPython 2.7.17 (default, Mar  8 2023, 18:40:28) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import roslib

In [2]: roslib.message.get_message_class('sensor_msgs/Image')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0658d0772c3c> in <module>()
----> 1 roslib.message.get_message_class('sensor_msgs/Image')

AttributeError: 'module' object has no attribute 'message'
```

**Comment by softyanija** [comment]
What commit message is proper? "import roslib.message explicitly to suport noetic"?

**Comment by tkmtnt7000** [comment]
Something like...
"Fix import roslib.message explicitly"

It is because the problem solved by this PR is not only for noetic or python3.

**Comment by softyanija** [comment]
I understood, and changed to "fixed to import roslib.message explicitly".

**Comment by tkmtnt7000** [comment]
Thank you. Wait for merging fixing CI commit in #1787

**Comment by k-okada** [comment]
closed via https://github.com/jsk-ros-pkg/jsk_common/pull/1788

**Pull request closed without merging**
