### PR TITLE
[jsk_topic_tools] merge topic_buffer tests and loose conditions

### PR DESCRIPTION
**Pull request by knorth55**
`topic_buffer` tests are tend to fail in GA because of CPU high load.
I merge the tests into one and loose the test condition.
https://github.com/jsk-ros-pkg/jsk_common/runs/6681349763?check_suite_focus=true
https://github.com/jsk-ros-pkg/jsk_common/runs/6681169482?check_suite_focus=true

### CODE REVIEW

**Comment by knorth55** [comment]
I merged `topic_buffer` test into one and loose the test conditions.

**Comment by knorth55** [comment]
Now test passed 💯

**Comment by knorth55** [comment]
Now test passed 💯

**Review by iory — APPROVED** [review]

**Comment by knorth55** [comment]
This PR stabilize the CI.
@k-okada can you check this PR?

@iory and I think that we the hztrst is too strict with `0.1` Hz, so we should change it to higher `Hz`.
in that case we can merge the three tests into one test, we thought.

**Comment by iory** [comment]
@k-okada 
The test of test_topic_buffer fails well. I would be grateful if you could merge this.
https://github.com/jsk-ros-pkg/jsk_common/runs/7087133800?check_suite_focus=true

**Comment by iory** [comment]
I commented out the tests and renamed the tests' extention `.test` to `.launch`.
https://github.com/jsk-ros-pkg/jsk_common/pull/1739/commits/b68928f3eca60da8da494a923da4ac23e8006c5f
https://github.com/jsk-ros-pkg/jsk_common/pull/1739/commits/f933115ed7156b204cebcd9b37d2a5ecfc82ec31

**Pull request merged**
