### PR TITLE
Use catkin tools

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by garaemon** [comment]
Please merge it after enough testing

I sincerely hope add test of hrpsys_ros_bridge to following jenkins at least http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/jsk.rosbuild

**Comment by garaemon** [comment]
devel/setup.bash directs wrong bashfile

```
$ pwd
/home/garaemon/ros_test/ros/hydro
$ source devel/setup.bash
devel/setup.bash:.:8: no such file or directory: /home/garaemon/ros_test/ros/hydro/setup.sh
```

**Comment by garaemon** [comment]
oops, it's my misunderstanding

**Comment by garaemon** [comment]
And I think repositories under start-jsk still uses old jsk_travis, we need to update them before merge it.

**Comment by garaemon** [comment]
```
$ rtmlaunch hrpsys_ros_bridge test-samplerobot.test | tee hoge.log
loading /home/garaemon/ros_test/ros/hydro_parent/devel/share/openhrp3/share/OpenHRP-3.1/sample/model/sample1.wrl
/home/garaemon/ros_test/ros/hydro_parent/devel/share/openhrp3/share/OpenHRP-3.1/sample/model/sample1.wrl cannot be found.
...
```

**Comment by garaemon** [comment]
```
$ rospack find hrpsys
/home/garaemon/ros_test/ros/hydro_parent/devel/share/hrpsys
```
Looks good!

**Comment by garaemon** [comment]
The problems I mentioned were solved?

**Comment by k-okada** [comment]
this one -> https://github.com/jsk-ros-pkg/jsk_common/pull/745#issuecomment-73353040

https://github.com/fkanehiro/openhrp3/commit/d81bdcf7e739786ab7e959181e1b8e05605e823d

**Comment by garaemon** [comment]
Good,I will confirm it works before deploying to robots

✉︎ Ryohei Ueda




On Sat, Feb 7, 2015 at 9:29 PM -0800, "Kei Okada" <notifications@github.com> wrote:












this one -> #745 (comment)



fkanehiro/openhrp3@d81bdcf

**Comment by garaemon** [comment]
How about use wstool instead of rtmros_common/setup.sh?
It's easy to keep tracking HEAD

✉︎ Ryohei Ueda




On Sat, Feb 7, 2015 at 9:29 PM -0800, "Kei Okada" <notifications@github.com> wrote:












this one -> #745 (comment)



fkanehiro/openhrp3@d81bdcf

**Comment by k-okada** [comment]
that's good idea, see https://github.com/start-jsk/rtmros_common/pull/654/files
I also change file name and require -w option to set install path, so that non-expert user run this script without knowing what's happens. once this PR is accepted we have to update jsk.rosbuid again...

**Pull request merged**
