### PR TITLE
[jsk.rosbuild] Use latest pip and setuptools

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
pip installed via apt is very old. (1.5.4)
the latest pip is 7.1.2.

**Comment by garaemon** [comment]
why we need latest pip?

2015年9月26日土曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> pip installed via apt is very old. (1.5.4)
> the latest pip is 7.1.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1133#issuecomment-143404729>
> .
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
Because rosdep requires newer pip than which is released via apt on Ubuntu 12.04.
https://github.com/jsk-ros-pkg/jsk_travis/pull/155
On 14.04, the situation is not so bad, but needed some workaround.
https://github.com/ros-infrastructure/rosdep/pull/411

At least, using newer pip than that on apt is required on Ubuntu 12.04.
So should we install latest pip only for hydro?

**Comment by garaemon** [comment]
> At least, using newer pip than that on apt is required on Ubuntu 12.04.

why? is there any problem on old pip? i haven't caught up yet

**Comment by wkentaro** [comment]
In the jsk_demos PR, the travis test fails only on hydro.
https://github.com/jsk-ros-pkg/jsk_demos/pull/1065#issuecomment-143402411
and the output was

**Comment by wkentaro** [comment]
like:
```
+ rosdep install -r -q -n --from-paths . /opt/ros/hydro/share --ignore-src --rosdistro hydro -y
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
WARNING: Package "ompl" does not follow the version conventions. It should not contain leading zeros (unless the number is 0).
Usage: pip COMMAND [OPTIONS]

pip: error: No command by the name pip show
  (maybe you meant "pip install show")

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.11.3

Bad installer [pip]: Command '['pip', 'show', 'fysom']' returned non-zero exit sta
```

And this is because of the pip released via apt on Ubuntu 12.04 is too old for rosdep.

**Comment by wkentaro** [comment]
Simply say, because old pip has no `pip show [package]` command.

**Comment by garaemon** [comment]
I see and the latest rosdep requires `pip show`, right?

**Comment by wkentaro** [comment]
Yes.

**Comment by wkentaro** [comment]
that is firstly added at https://github.com/ros-infrastructure/rosdep/commit/a0b7ea6369cc63fff0567fa96c1a9c6d9b810531.
And released rosdep with that commit after 0.11.1.

**Pull request merged**
