### PR TITLE
[jsk_tools] Add bullet for git-jsk-commit to beautify as markdown

### PR DESCRIPTION
**Pull request by wkentaro**
Modified:
  - jsk_tools/bin/git-jsk-commit

### CODE REVIEW

**Comment by wkentaro** [comment]
before

image


after 

image

**Comment by garaemon** [comment]
awesome!

**Comment by garaemon** [comment]
Let's add CONTRIBUTION.md to talk about jsk-commit subcommand

**Comment by wkentaro** [comment]
Could you please reopen https://github.com/jsk-ros-pkg/jsk_common/pull/1202 ?

**Pull request merged**
