### PR TITLE
[jsk_data] Add pep8 roslint for jsk_data/node_scripts

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
btw, how do I know if the code satisfy pep8 within my editor?

**Comment by wkentaro** [comment]
I think maybe https://github.com/flycheck/flycheck works.
@iory Could you please some helps?

**Comment by wkentaro** [comment]
@k-okada 
I found a solution of using [elpy](https://github.com/jorgenschaefer/elpy).
https://github.com/wkentaro/dotfiles/commit/1dd211f3e9a7cb4b25b7fcfef5569c9c95301841
screen shot 2016-11-24 at 7 49 09

**Comment by iory** [comment]
Sorry, I had also overlooked this issue. Please wait a minute

**Comment by iory** [comment]
@k-okada 
If you don't need auto code arrangement, flycheck is simple solution.

https://github.com/flycheck/flycheck
Please add flycheck into your emacs's load-path or install by melpa(https://github.com/melpa/melpa).
I recommend using melpa to install emacs package.

After install that,
please add following lines in .emacs.d/init.el
```
;; python settings
(require 'python)
(add-hook 'python-mode-hook 'flycheck-mode)
```

**Comment by k-okada** [comment]
is there deb-installable solution?

**Comment by wkentaro** [comment]
Merge this, please. 🙏

**Comment by k-okada** [comment]
please find 'easy' solution for emacs users.

--
◉ Kei Okada


2017-02-08 21:17 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Oh, OK.

**Comment by wkentaro** [comment]
Maybe this is too strict for people who is not Pythonista.

**Pull request closed without merging**
