### PR TITLE
Fix for OpenCV 3 installed from source

### PR DESCRIPTION
**Pull request by iKrishneel**
Please dont merge yet. 
-- Build Checking

### CODE REVIEW

**Comment by k-okada** [comment]
i think you do not have to #if #else for opencv3, your update code may work on opencv2, please try.

**Comment by iKrishneel** [comment]
When I changed the highgui header from 
`#include<opencv2/highgui.hpp>`
to
`#include<opencv2/highgui/highgui.hpp>`

I compiles on both versions as you mentioned and I removed the #if #else. 
I didnt realized that in OpenCV 3.0 the highgui.hpp is in both _opencv2/highgui.hpp_ and _opencv2/highgui/highgui.hpp_ unlike earlier version.

**Comment by k-okada** [comment]
please take a look at
https://github.com/ros-perception/vision_opencv/tree/indigo/opencv_apps/src/nodelet,
they are good example of writing code for running both oepncv2 and opencv3

--
◉ Kei Okada

**Comment by k-okada** [comment]
please rebase origin/master

**Comment by iKrishneel** [comment]
@k-okada 
I made a mess in the PR when squashing commits. 
Can I close and send cleaner PR?

**Comment by k-okada** [comment]
sure, of course!

--
◉ Kei Okada

**Pull request closed without merging**
