### PR TITLE
[jsk_tools] Generate deb release table with python script

### PR DESCRIPTION
**Pull request by wkentaro**
image

### CODE REVIEW

**Comment by k-okada** [comment]
nice, can you add arm build too?

**Comment by wkentaro** [comment]
Do you know what url is for arm build?
https://github.com/jsk-ros-pkg/jsk_common/pull/1490/files#diff-7cb9197ccd7d93f51b0e0668a047aceeR30

**Comment by k-okada** [comment]
http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__jsk_data__ubuntu_trusty_armhf__binary/

--
◉ Kei Okada


2016-11-29 12:07 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
screen shot 2016-11-29 at 12 26 04

**Comment by k-okada** [comment]
btw, do we need to install tabulate from pip?
```
Traceback (most recent call last):
  File "/opt/ros/indigo/share/jsk_tools/src/generate_deb_status_table.py", line 6, in <module>
    import tabulate
ImportError: No module named tabulate
```

**Comment by wkentaro** [comment]
Yeah, actually.

**Pull request merged**
