### PR TITLE
[jsk_tools] Add tool to make commit message informative

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #1202

This is proposed by @k-okada and discussed on #1202

Modified:
	 jsk_tools/env-hooks/99.jsk_tools.sh

### CODE REVIEW

**Comment by wkentaro** [comment]
Please run `jsk_git_commit_verbose` when committing.

**Comment by garaemon** [comment]
If you rename the function like `git-foo-bar`, is it possible to use like `git foo-bar`?

**Comment by wkentaro** [comment]
I think we need to create an executable which is named `git-foo-bar` to do that.

**Comment by garaemon** [comment]
I see

**Comment by wkentaro** [comment]
> If you rename the function like git-foo-bar, is it possible to use like git foo-bar?

Do you think it's better?

**Comment by garaemon** [comment]
> Do you think it's better?

I think so.

**Comment by wkentaro** [comment]
```
git jsk-commit
```
is ok?

**Pull request merged**
