### PR TITLE
add euslint: linter for euslisp

### PR DESCRIPTION
**Pull request by knorth55**
### What it is
- linter for euslisp
- add_euslint_test cmake function (new)

### Checking
- parenthesis mismatch
- invalid whitespace
- tab usage
- max line length (default=100, this is from https://google.github.io/styleguide/lispguide.xml)

#### Command Line

```
$ euslint test/
test/pr2-ri-test-simple.l:43: linelength: line too long (122 > 100 characters)
test/pr2-ri-test-simple.l:45: linelength: line too long (134 > 100 characters)
test/pr2-ri-test-simple.l:47: linelength: line too long (134 > 100 characters)
test/pr2-ri-test-simple.l:81: tab: line contains tab
test/pr2-ri-test-simple.l:82: tab: line contains tab
test/pr2-ri-test-simple.l:83: tab: line contains tab
test/pr2-ri-test-simple.l:84: tab: line contains tab
test/pr2-ri-test-simple.l:85: tab: line contains tab
test/pr2-ik-test.l:11: linelength: line too long (109 > 100 characters)
test/pr2-ik-test.l:13: whitespace: line contains invalid whitespace
test/pr2-grasp-test.l:14: whitespace: line contains invalid whitespace
test/pr2-read-state-test.l:22: tab: line contains tab
test/pr2-read-state-test.l:24: tab: line contains tab
test/pr2-read-state-test.l:26: tab: line contains tab
test/pr2-read-state-test.l:28: tab: line contains tab
...
....
```

```
$ euslint -i tab,whitespace test/
test/pr2-ri-test-simple.l:43: linelength: line too long (122 > 100 characters)
test/pr2-ri-test-simple.l:45: linelength: line too long (134 > 100 characters)
test/pr2-ri-test-simple.l:47: linelength: line too long (134 > 100 characters)
test/pr2-ik-test.l:11: linelength: line too long (109 > 100 characters)
...
...
```
#### CMakeLists.txt

add a line in CMakeLists.txt to check `euslisp/` dir

```
euslint_add_test(euslisp/)
# or
euslint_add_test(TARGET euslisp/)
```

output is like below

```
$ cat euslint__home_shingo_ros_indigo_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="0" time="1" errors="0" name="_home_shingo_ros_indigo_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp">
  <testcase name="test_ran" status="run" time="1" classname="Results">
  </testcase>
</testsuite>
```

add option as below

```
euslint_add_test(TARGET euslisp/ OPTION "-l 80")
```

```
$ cat euslint__home_shingo_ros_indigo_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="_home_shingo_ros_indigo_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp">
  <testcase name="test_ran" status="run" time="1" classname="Results">
  <failure message="shell test with command [/home/shingo/ros/indigo/src/jsk-ros-pkg/jsk_common/jsk_tools/bin/euslint /home/shingo/ros/indigo/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc/euslisp -l 80] failed" type=""/>
  </testcase>
  <system-out><![CDATA[[
/home/shingo/ros/indigo/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc/euslisp/main.l:82: linelength: line too long (95 > 80 characters)
/home/shingo/ros/indigo/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc/euslisp/main.l:192: linelength: line too long (87 > 80 characters)
/home/shingo/ros/indigo/src/start-jsk/jsk_apc/jsk_2016_01_baxter_apc/euslisp/main.l:202: linelength: line too long (99 > 80 characters)
...
...
```
### Options

```
$ euslint --help
usage: euslint [-h] [-e EXTENSION] [-l MAX_LINELENGTH] [-i IGNORE] path

positional arguments:
  path                  checking dir or file path

optional arguments:
  -h, --help            show this help message and exit
  -e EXTENSION, --extension EXTENSION
                        file extension, defalut: l
  -l MAX_LINELENGTH, --max-linelength MAX_LINELENGTH
                        maximum line length, defalut: 100
  -i IGNORE, --ignore IGNORE
                        list of ignoring check ids.
```

### CODE REVIEW

**Comment by k-okada** [comment]
you can send PR to http://github.com/euslisp/EusLisp or
http://github.com/euslisp/jskeus

--
◉ Kei Okada


2016-10-28 2:38 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
i want to make cmake test function with this, therefore i thought ros package might be better

**Comment by knorth55** [comment]
I added cmake test function of euslisp linter

**Comment by wkentaro** [comment]
> i want to make cmake test function with this, therefore i thought ros package might be better

- euslint -> euslisp or jskeus
- euslint-test.cmake -> roseus

seems better, what do you think?

**Comment by knorth55** [comment]
> euslint -> euslisp or jskeus
is this that core function?

> euslint-test.cmake -> roseus
i have no idea. both seems fine for me

**Comment by wkentaro** [comment]
Well, I think sending PR to euslisp or jskeus and roseus is better, but it takes more time.
Placing jsk_tools is a temporary solution, because some users would like to use Euslisp without ROS and euslint is useful in that case.
So it's up to you.

**Comment by knorth55** [comment]
i will make PR to euslisp or jskeus, and cmake function PR to roseus.

but what i want to do is cmake function.
I'm not familiar with cmake, and making this function in roseus takes much time (but i want to do)
now i  should work on other programs, so i want to put this in jsk_tools for temporary solution.

**Comment by knorth55** [comment]
i had a debate with @wkentaro and we concluded to move this linter to euslisp/euslisp repo

**Comment by knorth55** [comment]
@k-okada I made a PR to euslisp https://github.com/euslisp/EusLisp/pull/209

**Comment by knorth55** [comment]
TODO: make PR for euslint cmake function

**Pull request closed without merging**
