### PR TITLE
Update jsk_travis to 8634b5

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
let's add version number to jsk_travis

**Comment by wkentaro** [comment]
You mean in the commit message?

2015年10月19日月曜日、Kei Okada<notifications@github.com>さんは書きました:

> let's add version number to jsk_travis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1192#issuecomment-149065385>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
no, please ask for releasing new version of jsk_travis, if you think you
have done with jsk_travis upgrade.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Ok.

**Comment by wkentaro** [comment]
I wil send another PR after the new release of jsk_travis.

**Pull request closed without merging**
