### PR TITLE
[speak_and_wait_recovery] add speak_and_wait_recovery

### PR DESCRIPTION
**Pull request by sktometometo**
Add a RecoveryBehavior plugin package which enables a robot to speak and wait when get stuck.

https://user-images.githubusercontent.com/9410362/113476175-ce3c1400-94b4-11eb-87fa-8f7cdafb1d62.mp4

TODO
- [x] Make a image
- [x] Add tests
- ~[ ] Prepair demo launch files~

### CODE REVIEW

**Comment by sktometometo** [comment]
A Test is added. Now ready for reviewing.

**Review by 708yamaguchi — COMMENTED** [review]
Nice.
I feel that this plugin works well in real fetch robots.

I think it would be helpful if you add sample usage or sample file of this plugin to README.md.

**Comment by sktometometo** [comment]
A demo.launch is added.

**Review by 708yamaguchi — APPROVED** [review]
thank you!

**Comment by k-okada** [comment]
test failing 

https://github.com/jsk-ros-pkg/jsk_common/pull/1681/checks?check_run_id=2801465685
```
  [speak_and_wait_recovery:make] [speak_and_wait_recovery.rosunit-speak_and_wait_recovery/test_publish][FAILURE]-
  
                                                                                  
  [speak_and_wait_recovery:make] Topic [/sound_play/goal] is not published
```

**Comment by sktometometo** [comment]
@k-okada All tests have passed.

**Comment by k-okada** [comment]
@sktometometo nice work, btw did we discuss which repository to put this package in? I am woundering why we put this in  jsk_common, instead of  jsk_robot. Maybe I have said something before....

**Comment by sktometometo** [comment]
Moved to https://github.com/jsk-ros-pkg/jsk_robot/pull/1396

**Pull request closed without merging**
