### PR TITLE
Check host sanity with a script

### PR DESCRIPTION
**Pull request by wkentaro**
screenshot from 2016-12-01 23 49 54

### CODE REVIEW

**Comment by k-okada** [comment]
need documentation?

**Comment by wkentaro** [comment]
Updated.

**Comment by wkentaro** [comment]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

... Why?

**Comment by k-okada** [comment]
restarted jenkins

**Comment by wkentaro** [comment]
@h-kamada Could you please review this? I hope this script help you to fix some troubles on using multiple robots.

**Comment by k-okada** [comment]
@wkentaro please add your name to jsk_data package.

**Comment by wkentaro** [comment]
@k-okada Is this ok for you? https://github.com/jsk-ros-pkg/jsk_common/pull/1501

**Comment by k-okada** [comment]
thx

**Pull request merged**
