### PR TITLE
[jsk.rosinstall.hydro] Add catkin to install from source

### PR DESCRIPTION
**Pull request by wkentaro**
To avoid Bug: https://github.com/ros/catkin/issues/686
Issue: https://github.com/jsk-ros-pkg/jsk_common/issues/885

### CODE REVIEW

**Comment by wkentaro** [comment]
catkin does not have `hydro-devel` branch.

**Comment by k-okada** [comment]
Hum

Who need to use zsh on hydro?

**Comment by wkentaro** [comment]
I don't really know about each person's shell preference.
But the problem is also described in https://github.com/jsk-ros-pkg/trans_system/pull/238 .

**Comment by wkentaro** [comment]
And I do use zsh on hydro.

**Comment by k-okada** [comment]
I think you do not have to use hydro.

2015年6月16日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> And I do use zsh on hydro.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/995#issuecomment-112150540>
> .
>


-- 
--
◉ Kei Okada

**Comment by garaemon** [comment]
I'm using zsh on hydro and I have no problem though

**Comment by garaemon** [comment]
Anyway, I think this commit has no problem for us.

**Comment by k-okada** [comment]
no problem at this moment, but I'm afraid this will have some trouble in
future.

If we can assume new version of catkin within a few weeks/month, we will
revert this PR. but most user did not realize that and they did not know
how to handle such case, then they will still use old version of catkin or
latest version of catkin. If this PR is required only for two super expert
developer, we'll better to keep this as PR and ask them to merge by them
self or manually install latest version of catkin.


--
◉ Kei Okada

**Comment by wkentaro** [comment]
I get your point.
It seems that we should avoid to add `ros/catkin` to the common `.rosinstall`.

**Pull request closed without merging**
