### PR TITLE
[jsk_tools/env-hooks/99.jsk_tools.sh] use ip for rossetip instead of ifconfig

### PR DESCRIPTION
**Pull request by furushchev**
for future compatibility and multi platform.

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada Test passed. Please merge.

**Comment by k-okada** [comment]
1) ip is provided from iproute2 package, did you add rosdep for this?
```
$ dpkg -S /bin/ip
iproute2: /bin/ip
```

2) do we have test code ros rossetip?

3) is this just a refactor ? or you have ane specific reason to change code?

**Comment by furushchev** [comment]
@k-okada Thank you for reviewing.

> 1) ip is provided from iproute2 package, did you add rosdep for this?

No, just forgot. I'll add it.

> 2) do we have test code ros rossetip?
 
No, I think. I should add test code. (but a bit difficult)

> 3) is this just a refactor ? or you have ane specific reason to change code?

current implementation uses `ifconfig`. this is deprecated and will be removed in the future. (already unavailable on OSX), and replaced to `ip`.

Also `ip` provides function to get route from specific device to host and it's much smarter to use this instead of masking manually. (https://github.com/jsk-ros-pkg/jsk_common/pull/1436/files#diff-48005ba849f01087afb5a38e0561c822L97)

Also I fixed weird behavior in `rossetip_addr`, which captures ip address of `docker0` when docker is installed.

**Comment by furushchev** [comment]
@k-okada How about this pull request?

**Comment by k-okada** [comment]
Did you ass iproute2 to package.xml ?

**Comment by furushchev** [comment]
@k-okada Oh,,, very sorry... added.

**Comment by k-okada** [comment]
memo:
- users do not install from scratch, they just update the code
- when users have trouble, they roll back code to previous version
https://github.com/jsk-ros-pkg/jsk_common/issues/1472#issuecomment-256624899

**Pull request merged**
