### PR TITLE
[jsk.rosbuild] Print message when jsk.rosbuild finishes

### PR DESCRIPTION
**Pull request by garaemon**
see https://github.com/jsk-ros-pkg/jsk_common/issues/861

### CODE REVIEW

**Comment by k-okada** [comment]
```
]2;[build] 27/29[collada_urdf_jsk_patch] Branch hydro-devel set up to track remote branch hydro-devel from origin. 
]2;[build] 27/29[collada_urdf_jsk_patch] HEAD is now at 188eb5a 1.10.21                         
]2;[build] 27/29[collada_urdf_jsk_patch] patching file collada_urdf/CMakeLists.txt              
]2;[build] 27/29[collada_urdf_jsk_patch] Hunk #1 succeeded at 12 with fuzz 2 (offset -3 lines). 
]2;[build] 27/29[collada_urdf_jsk_patch] patching file collada_urdf/src/collada_urdf.cpp        
]2;[build] 27/29[collada_urdf_jsk_patch] patching file collada_urdf/src/collada_to_urdf.cpp     
]2;[build] 27/29[collada_urdf_jsk_patch] patching file collada_urdf/src/collada_to_urdf.cpp     
]2;[build] 27/29[collada_urdf_jsk_patch] patched                                                
]2;[build] 27/29[collada_urdf_jsk_patch] ImportError: "from catkin_pkg.topological_order import topological_order" failed: No module named tool_detection 
]2;[build] 27/29[collada_urdf_jsk_patch] Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH. 
]2;[build] 27/29[collada_urdf_jsk_patch] make[3]: *** [urdf_to_collada] Error 1                 
]2;[build] 27/29[collada_urdf_jsk_patch] make[2]: *** [/home/travis/ros/ws_jsk_common/devel/lib/collada_urdf_jsk_patch/urdf_to_collada] Error 2 
]2;[build] 27/29[collada_urdf_jsk_patch] make[1]: *** [CMakeFiles/urdf_to_collada.dir/all] Error 2 
]2;[build] 27/29[collada_urdf_jsk_patch] make: *** [all] Error 2                                
]2;[build] 27/29[collada_urdf_jsk_patch] <== '/home/travis/ros/ws_jsk_common/build/collada_urdf_jsk_patch/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2' 
]2;[build] 27/29Failed   <== collada_urdf_jsk_patch   [ 37.9 seconds ]         
```

**Comment by garaemon** [comment]
This commit https://github.com/ros-infrastructure/catkin_pkg/commit/1e41ff555d6501cead8eb44265814f03c1c35329

**Comment by garaemon** [comment]
[this catkin_make](https://github.com/jsk-ros-pkg/jsk_3rdparty/blob/master/jsk_ros_patch/collada_urdf_jsk_patch/Makefile#L16) produces the error

**Comment by k-okada** [comment]
yes, I'm tyring to switch to catkin, but I really want to remove **_jsk_patch, they should be merged in the upstream.

**Comment by k-okada** [comment]
restarted travis, this should pass test with https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/12

**Pull request merged**
