### PR TITLE
[jsk.rosinstall.jade] create jsk.rosinstall.jade

### PR DESCRIPTION
**Pull request by furushchev**
- [jsk.rosinstall.jade] create jsk.rosinstall.jade
- [jsk.rosinstall.jade] add rospeex

ref: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1249

### CODE REVIEW

**Comment by furushchev** [comment]
travis failed with curious error

```
    raise RLException("roscore cannot run as another roscore/master is already running. \nPlease kill other roscore/master processes before relaunching.\nThe ROS_MASTER_URI is %s"%(m.uri))
```

```
[ROSTEST]-----------------------------------------------------------------------





SUMMARY

[1;31m * RESULT: FAIL[0m

 * TESTS: 0

[1;31m * ERRORS: 3[0m

 * FAILURES: 0



rostest log file is in /home/travis/.ros/log/rostest-testing-worker-linux-a1362517-2-523-linux-4-86385428-2167.log

-- run_tests.py: verify result "/home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_topic_buffer_fixed_rate.xml"

Built target _run_tests_jsk_topic_tools_rostest_test_test_topic_buffer_fixed_rate.test

[35m[1mScanning dependencies of target _run_tests_jsk_topic_tools_rostest_test_test_hz_measure.test

[0m-- run_tests.py: execute commands

  /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_jsk_common/src/jsk_common/jsk_topic_tools --package=jsk_topic_tools --results-filename test_test_hz_measure.xml --results-dir /home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results /home/travis/ros/ws_jsk_common/src/jsk_common/jsk_topic_tools/test/test_hz_measure.test 

... logging to /home/travis/.ros/log/rostest-testing-worker-linux-a1362517-2-523-linux-4-86385428-2201.log

Another rostest instance is currently running, waiting until it finished...

[ROSUNIT] Outputting test results to /home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_lightweight_throttle.xml

testhztest_lightweight_throttle ... ERROR!

ERROR: roscore cannot run as another roscore/master is already running. 

Please kill other roscore/master processes before relaunching.

The ROS_MASTER_URI is http://testing-worker-linux-a1362517-2-523-linux-4-86385428:22422/

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run

    testMethod()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn

    succeeded, failed = self.test_parent.launch()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 81, in launch

    return self.runner.launch()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 644, in launch

    self._setup()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 620, in _setup

    self._launch_master()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 381, in _launch_master

    raise RLException("roscore cannot run as another roscore/master is already running. \nPlease kill other roscore/master processes before relaunching.\nThe ROS_MASTER_URI is %s"%(m.uri))

--------------------------------------------------------------------------------



[ROSTEST]-----------------------------------------------------------------------





SUMMARY

[1;31m * RESULT: FAIL[0m

 * TESTS: 0

[1;31m * ERRORS: 1[0m

 * FAILURES: 0



rostest log file is in /home/travis/.ros/log/rostest-testing-worker-linux-a1362517-2-523-linux-4-86385428-2201.log

-- run_tests.py: verify result "/home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_lightweight_throttle.xml"

Built target _run_tests_jsk_topic_tools_rostest_test_test_lightweight_throttle.test

[35m[1mScanning dependencies of target _run_tests_jsk_topic_tools_rostest_test_test_block.test

[0m-- run_tests.py: execute commands

  /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_jsk_common/src/jsk_common/jsk_topic_tools --package=jsk_topic_tools --results-filename test_test_block.xml --results-dir /home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results /home/travis/ros/ws_jsk_common/src/jsk_common/jsk_topic_tools/test/test_block.test 

... logging to /home/travis/.ros/log/rostest-testing-worker-linux-a1362517-2-523-linux-4-86385428-2263.log

Another rostest instance is currently running, waiting until it finished...

[ROSUNIT] Outputting test results to /home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_hz_measure.xml

testtest_hz_measure ... ERROR!

ERROR: roscore cannot run as another roscore/master is already running. 

Please kill other roscore/master processes before relaunching.

The ROS_MASTER_URI is http://testing-worker-linux-a1362517-2-523-linux-4-86385428:22422/

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run

    testMethod()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn

    succeeded, failed = self.test_parent.launch()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 81, in launch

    return self.runner.launch()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 644, in launch

    self._setup()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 620, in _setup

    self._launch_master()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 381, in _launch_master

    raise RLException("roscore cannot run as another roscore/master is already running. \nPlease kill other roscore/master processes before relaunching.\nThe ROS_MASTER_URI is %s"%(m.uri))

--------------------------------------------------------------------------------



[ROSTEST]-----------------------------------------------------------------------





SUMMARY

[1;31m * RESULT: FAIL[0m

 * TESTS: 0

[1;31m * ERRORS: 1[0m

 * FAILURES: 0



rostest log file is in /home/travis/.ros/log/rostest-testing-worker-linux-a1362517-2-523-linux-4-86385428-2263.log

-- run_tests.py: verify result "/home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_hz_measure.xml"

Built target _run_tests_jsk_topic_tools_rostest_test_test_hz_measure.test

... logging to /home/travis/.ros/log/rostest-testing-worker-linux-a1362517-2-523-linux-4-86385428-2297.log

[ROSUNIT] Outputting test results to /home/travis/ros/ws_jsk_common/build/jsk_topic_tools/test_results/jsk_topic_tools/rostest-test_test_block.xml

testtest_block ... ERROR!

ERROR: roscore cannot run as another roscore/master is already running. 

Please kill other roscore/master processes before relaunching.

The ROS_MASTER_URI is http://testing-worker-linux-a1362517-2-523-linux-4-86385428:22422/

  File "/usr/lib/python2.7/unittest/case.py", line 327, in run

    testMethod()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn

    succeeded, failed = self.test_parent.launch()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 81, in launch

    return self.runner.launch()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 644, in launch

    self._setup()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 620, in _setup

    self._launch_master()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/launch.py", line 381, in _launch_master

    raise RLException("roscore cannot run as another roscore/master is already running. \nPlease kill other roscore/master processes before relaunching.\nThe ROS_MASTER_URI is %s"%(m.uri))
```

**Comment by furushchev** [comment]
anyway in my branch it passed test.
https://travis-ci.org/furushchev/jsk_common/builds/86385339

**Comment by k-okada** [comment]
let's use deb version, if it is not released yet, ask maintainer.

**Comment by furushchev** [comment]
@k-okada Already asked to maintainer. Sadly they does not open issue for "OTONA" reason. So I sent e-mail.

**Comment by k-okada** [comment]
humm, if so , we'd better to avoid such OTONA package...

--
◉ Kei Okada

**Comment by garaemon** [comment]
May CATKIN_PARALLEL_TEST_JOBS and ROS_PARALLEL_TEST_JOBS  solve the issue.
https://github.com/jsk-ros-pkg/jsk_travis/pull/176

in hydro, rostest looked not stable in parallel processing, because it just detected other rostest processes by pooling.
It meant multiple rostest may run.

But it should be fixed in https://github.com/ros/ros_comm/pull/468/files

**Comment by furushchev** [comment]
Once I close this PR since discussion above.

**Pull request closed without merging**
