### PR TITLE
[jsk_data] Record bag for rviz

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
how to use this?

**Comment by wkentaro** [comment]
I added documentation.

**Comment by garaemon** [comment]
same to --node option?
```
$ rosbag record --node=/foo_rviz
$ rosbag record -h
  --node=NODE           record all topics subscribed to by a specific node
```

**Comment by garaemon** [comment]
And also [this pr](https://github.com/ros-visualization/rqt_common_plugins/pull/348) enables `--node` with rqt_bag GUI.

**Comment by wkentaro** [comment]
> same to --node option?

Yes, but I didn't know that option. Thank you.

> And also this pr enables --node with rqt_bag GUI.

Thanks for the info.

**Pull request closed without merging**
