### PR TITLE
[jsk_network_tools] Kill child process at the end of process in silve…

### PR DESCRIPTION
**Pull request by garaemon**
…rhammer_highspeed_receiver.py

@furushchev is it correct?

### CODE REVIEW

**Comment by garaemon** [comment]
ping @furushchev

**Comment by furushchev** [comment]
@garaemon Sorry for late response.
I could not understand what you want to change.
we are already checking if we need to kill child process by checking at https://github.com/garaemon/jsk_common/blob/89fdb1358e34fedaa368eaaeefa06d1f01ab8f74/jsk_network_tools/scripts/silverhammer_highspeed_receiver.py#L128
Is there any problem?

**Comment by garaemon** [comment]
> Is there any problem?

Yes sometimes child process would be a zombie.

**Comment by garaemon** [comment]
I see, `rospy.on_shutdown` is just a registration of hook function.

However, it will not be called if a process is killed by SIGTERM, which is fired by roslaunch.

**Comment by furushchev** [comment]
@garaemon Thank you very much for clarifying! Now I think it's ok to merge!

**Comment by garaemon** [comment]
finally section does not run if SIGTERM is fired.

**Comment by garaemon** [comment]
Is it difficult to implement without multiprocessing?

two ideas:
1) Use cython
2) Use c++ to concatenate packets (use roscpp?)

**Pull request closed without merging**
