### PR TITLE
[jsk_data] Synchronize properly with slop for slow topics

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
```
[voice_text] CMake Error at /opt/ros/hydro/share/catkin/cmake/catkin_package.cmake:163 (message):
[voice_text]   catkin_package() DEPENDS on 'nkf' which must be find_package()-ed before.
[voice_text]   If it is a catkin package it can be declared as CATKIN_DEPENDS instead
[voice_text]   without find_package()-ing it.
[voice_text] Call Stack (most recent call first):
[voice_text]   /opt/ros/hydro/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
[voice_text]   CMakeLists.txt:16 (catkin_package)
[voice_text] 
[voice_text] 
[voice_text] -- Configuring incomplete, errors occurred!
[voice_text] <== '/workspace/ros/ws_jsk_common/build/voice_text/build_env.sh /usr/bin/cmake /workspace/ros/ws_jsk_common/src/jsk-ros-pkg/jsk_3rdpart
```

**Comment by furushchev** [comment]
maybe need to wait https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/68

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by k-okada** [comment]
40

**Pull request merged**
