### PR TITLE
fix for error when using opencv3

### PR DESCRIPTION
**Pull request by iKrishneel**
PR related to https://github.com/jsk-ros-pkg/jsk_common/pull/1354 with correct indentation

### CODE REVIEW

**Comment by k-okada** [comment]
may be https://github.com/jsk-ros-pkg/jsk_common/pull/1377 solves your problem, if not please reopen

**Comment by iKrishneel** [comment]
No it does not solve the problem. 

This line fix https://github.com/jsk-ros-pkg/jsk_common/pull/1358/files#diff-07c8da014511eb62b187f89f14031c80R1701

solves the NULL Pointer error. 
err

**Comment by k-okada** [comment]
I see, please rebase origin/master

**Comment by k-okada** [comment]
thanks, created new PR with rebased origin/master -> https://github.com/jsk-ros-pkg/jsk_common/pull/1387

**Comment by iKrishneel** [comment]
@k-okada  sensei,
I am sorry i overlooked it. 
I dont need to rebase now right?

**Comment by k-okada** [comment]
no, please check if latest origin/master work for you.

**Comment by iKrishneel** [comment]
I tested the latest master and it works. :+1:

**Pull request closed without merging**
