### PR TITLE
Update jsk_travis

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
same error, not yet resolved.
```
 /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/workspace/ros/ws_jsk_common/src/jsk_common/jsk_network_tools --package=jsk_network_tools --results-filename test_test_all_type_low_speed.xml --results-base-dir /workspace/ros/ws_jsk_common/build/jsk_network_tools/test_results /workspace/ros/ws_jsk_common/src/jsk_common/jsk_network_tools/test/test_all_type_low_speed.test 
... logging to /workspace/jsk-ros-pkg/jsk_common/log/rostest-e92918266336-8154.log
[ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_common/build/jsk_network_tools/test_results/jsk_network_tools/rostest-test_test_all_type_low_speed.xml
testtest_all_type_low_speed ... FAILURE!
FAILURE: Package [jsk_network_tools] for test node [jsk_network_tools/test_all_type_low_speed.py] does not exist
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 93, in fn
    self.fail(message)
  File "/usr/lib/python2.7/unittest/case.py", line 412, in fail
    raise self.failureException(msg)
```

**Comment by wkentaro** [comment]
We can use `rostest --text` to view the stdout while the test in below line
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L201

**Comment by wkentaro** [comment]
I sent PR with --text option at running rostest in install space.
 https://github.com/jsk-ros-pkg/jsk_travis/pull/165

**Comment by k-okada** [comment]
https://github.com/ros/catkin/pull/705/files is designed to show the output
of rostest

--
◉ Kei Okada

**Comment by wkentaro** [comment]
So does it show the test result of catkin run_tests also?

2015年10月13日火曜日、Kei Okada<notifications@github.com>さんは書きました:

> https://github.com/ros/catkin/pull/705/files is designed to show the
> output
> of rostest
>
> --
> ◉ Kei Okada
>
>
> On Tue, Oct 13, 2015 at 1:53 AM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I sent PR with --text option at running rostest in install space.
> > jsk-ros-pkg/jsk_travis#165
> > <https://github.com/jsk-ros-pkg/jsk_travis/pull/165>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/pull/1176#issuecomment-147459611
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1176#issuecomment-147582527>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
And the reason we do not have the log at present is travis.sh exist before
catkin test_results?

2015年10月13日火曜日、Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> So does it show the test result of catkin run_tests also?
>
> 2015年10月13日火曜日、Kei Okada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> https://github.com/ros/catkin/pull/705/files is designed to show the
>> output
>> of rostest
>>
>> --
>> ◉ Kei Okada
>>
>>
>> On Tue, Oct 13, 2015 at 1:53 AM, Kentaro Wada <notifications@github.com>
>> wrote:
>>
>> > I sent PR with --text option at running rostest in install space.
>> > jsk-ros-pkg/jsk_travis#165
>> > <https://github.com/jsk-ros-pkg/jsk_travis/pull/165>
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/jsk-ros-pkg/jsk_common/pull/1176#issuecomment-147459611
>> >
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsk-ros-pkg/jsk_common/pull/1176#issuecomment-147582527>
>> .
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by garaemon** [comment]
In this failure, rostest failed to find package. `rostest --t` does not help us so much.

**Comment by wkentaro** [comment]
You mean `FAILURE: Package [jsk_network_tools] for test node [jsk_network_tools/test_all_type_low_speed.py] does not exist`. I overlooked it.

**Comment by wkentaro** [comment]
> https://github.com/ros/catkin/pull/705/files is designed to show the output
of rostest

the problem is these lines are not executed when failed?
 https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L213-L215

**Comment by k-okada** [comment]
> [jsk_network_tools/test_all_type_low_speed.py] does not exist

You may forget to install that file or forget to +x bit.

**Comment by wkentaro** [comment]
> You may forget to install that file or forget to +x bit.

I'm talking about enhancement of logs of jsk_travis. 
So let's move this discussion to https://github.com/jsk-ros-pkg/jsk_travis/pull/166

**Comment by garaemon** [comment]
> You may forget to install that file or forget to +x bit.

Restarting solves this issue, so executable bit should be set correctly.

**Comment by garaemon** [comment]
I hoped https://github.com/jsk-ros-pkg/jsk_travis/pull/164 and https://github.com/jsk-ros-pkg/jsk_travis/pull/162 would solve this issue.

**Pull request closed without merging**
