### PR TITLE
[jsk_tools] Remove ws_doctor.py

### PR DESCRIPTION
**Pull request by wkentaro**
wstool>=0.1.12 does show equivalent information by ``wstool info``

### CODE REVIEW

**Comment by wkentaro** [comment]
```
$ wstool info
workspace: /home/wkentaro/ros/indigo/src

 Localname                        S SCM  Version (Spec)                           UID  (Spec)                 URI  (Spec) [http(s)://...]
 ---------                        - ---- --------------                           -----------                 ---------------------------
 RethinkRobotics/baxter_tools       git  <detached>  (v1.1.0)                     600dea61562a                github.com/RethinkRobotics/baxter_tools.git
 RethinkRobotics/baxter_simulator   git  <detached>  (v0.9.0)                     69068c763351                git@github.com:RethinkRobotics/baxter_simulator.git
 RethinkRobotics/baxter_interface   git  <detached>  (v1.1.0)                     990bb659f2bd                github.com/RethinkRobotics/baxter_interface.git
 RethinkRobotics/baxter_examples    git  <detached>  (v1.1.0)                     4685b099c738                github.com/RethinkRobotics/baxter_examples.git
 RethinkRobotics/baxter_common      git  fix_simple_urdf_v_1_1_0                  835c39d51b21                github.com/k-okada/baxter_common.git
 RethinkRobotics/baxter             git  <detached>  (v1.1.0)                     058146c8a999                github.com/RethinkRobotics/baxter.git
 ros-perception/perception_pcl      git  indigo-devel                             0f8694e15824                github.com/ros-perception/perception_pcl.git
 wkentaro/ros-pkg                   git  master                                   0c1c1c60462e                github.com/wkentaro/ros-pkg.git
 start-jsk/jsk_apc                  git  master                                   c4b2f590d97b                github.com/start-jsk/jsk_apc.git
 jsk-ros-pkg/openrave_planning      git  master                                   2da7bcc79128                github.com/jsk-ros-pkg/openrave_planning.git
 jsk-ros-pkg/jsk_visualization      git  master                                   bc02df3173ce                github.com/jsk-ros-pkg/jsk_visualization.git
 jsk-ros-pkg/jsk_travis             git  master                                   01479150f721                github.com/jsk-ros-pkg/jsk_travis.git
 jsk-ros-pkg/jsk_smart_apps       V git  empty-pr  (master)                       859804136b91 (248e74ef17c1) github.com/jsk-ros-pkg/jsk_smart_apps.git
 jsk-ros-pkg/jsk_roseus             git  master                                   3dcf3646b8cc                github.com/jsk-ros-pkg/jsk_roseus.git
 jsk-ros-pkg/jsk_robot              git  master                                   50282bb1361a                github.com/jsk-ros-pkg/jsk_robot.git
 jsk-ros-pkg/jsk_recognition      V git  fast-rcnn < wkentaro/fast-rcnn  (master) 467b69b6276e (438c63a80199) github.com/jsk-ros-pkg/jsk_recognition.git
 jsk-ros-pkg/jsk_pr2eus             git  master                                   517a4702a10e                github.com/jsk-ros-pkg/jsk_pr2eus.git
 jsk-ros-pkg/jsk_planning           git  master                                   13619e5fe87a                github.com/jsk-ros-pkg/jsk_planning.git
 jsk-ros-pkg/jsk_openni_kinect      git  master                                   2aa4b1cb8006                github.com/jsk-ros-pkg/jsk_openni_kinect.git
 jsk-ros-pkg/jsk_model_tools        git  master                                   b76687c4500e                github.com/jsk-ros-pkg/jsk_model_tools.git
 jsk-ros-pkg/jsk_demos              git  master                                   e25759d7541c                github.com/jsk-ros-pkg/jsk_demos.git
 jsk-ros-pkg/jsk_control            git  master                                   d53affc1279b                github.com/jsk-ros-pkg/jsk_control.git
 jsk-ros-pkg/jsk_common_msgs        git  master                                   d10f85577809                github.com/jsk-ros-pkg/jsk_common_msgs.git
 jsk-ros-pkg/jsk_common           V git  seek-stable-testing  (master)            ac3c6e153a72 (d5adacd4b578) github.com/jsk-ros-pkg/jsk_common.git
 jsk-ros-pkg/jsk_3rdparty           git  master                                   1d836d2a4a79                github.com/jsk-ros-pkg/jsk_3rdparty.git
```

**Comment by wkentaro** [comment]
Please merge.

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_common/commits/master/jsk_tools/bin/ws_doctor.py

do we need to remove function in sanity_lib.py or not?

p.s.
this is good example
1. writing my own tool
2 .move function to another place
3. tool is no longer needed, because upstream tool support them
4 so, what should we do about moved function.

if we first update upstream tools, then nothing happens.


--
◉ Kei Okada

**Comment by k-okada** [comment]
better to wait for their pre-defence and enshu.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
the author ws_doctor.py is not me.
so this is not the case.

I don't know anything about sanity_lib.py.

2015年11月12日木曜日、Kei Okada<notifications@github.com>さんは書きました:

>
> https://github.com/jsk-ros-pkg/jsk_common/commits/master/jsk_tools/bin/ws_doctor.py
>
> do we need to remove function in sanity_lib.py or not?
>
> p.s.
> this is good example
> 1. writing my own tool
> 2 .move function to another place
> 3. tool is no longer needed, because upstream tool support them
> 4 so, what should we do about moved function.
>
> if we first update upstream tools, then nothing happens.
>
>
> --
> ◉ Kei Okada
>
>
> On Thu, Nov 12, 2015 at 5:20 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Please merge.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_common/pull/1211#issuecomment-156031424
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_common/pull/1211#issuecomment-156032249>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
> better to wait for their pre-defence and enshu.

I don't understand what you mean..

**Comment by garaemon** [comment]
we can remove it

**Pull request merged**
