### PR TITLE
Add test for data_collection_server

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/jsk-ros-pkg/jsk_common/pull/1598
Close #1596

### CODE REVIEW

**Comment by wkentaro** [comment]
```
libdc1394 error: Failed to initialize libdc1394

ImportError: numpy.core.multiarray failed to import

Traceback (most recent call last):

  File "/home/travis/ros/ws_jsk_common/install/share/jsk_topic_tools/scripts/static_image_publisher.py", line 3, in <module>

    import cv2

ImportError: numpy.core.multiarray failed to import
```

**Comment by wkentaro** [comment]
```
[ROSUNIT] Outputting test results to /home/travis/.ros/test_results/jsk_data/rostest-tests_data_collection_server.xml

Traceback (most recent call last):

  File "/home/travis/ros/ws_jsk_common/install/share/jsk_topic_tools/scripts/static_image_publisher.py", line 4, in <module>

    from scipy.misc import face

  File "/usr/lib/python2.7/dist-packages/scipy/misc/__init__.py", line 57, in <module>

    from .pilutil import *

  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 20, in <module>

    from PIL import Image, ImageFilter

  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 88, in <module>

    import builtins

KeyboardInterrupt

Traceback (most recent call last):

  File "/opt/ros/indigo/lib/rostopic/rostopic", line 35, in <module>

    rostopic.rostopicmain()

  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostopic/__init__.py", line 1926, in rostopicmain

    _rostopic_cmd_pub(argv)

  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostopic/__init__.py", line 1595, in _rostopic_cmd_pub

    pub, msg_class = create_publisher(topic_name, topic_type, latch)

  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostopic/__init__.py", line 1429, in create_publisher

    rospy.init_node('rostopic', anonymous=True, disable_rosout=True, disable_rostime=True)

  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 320, in init_node

    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")

rospy.exceptions.ROSInitException: init_node interrupted before it could complete

testtest_data_collection_server ... FAILURE!

FAILURE: Test Fixture Nodes ['data_collection_server_request', 'data_collection_server_timer', 'data_collection_server_all'] failed to launch

  File "/usr/lib/python2.7/unittest/case.py", line 331, in run

    testMethod()

  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn

    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)

  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue

    raise self.failureException(msg)
```

**Comment by wkentaro** [comment]
Actually, I can't find how to fix the error on travis..

**Comment by k-okada** [comment]
@wkentaro I could reproduce this problem by
```
virtualenv venv
cd venv
. ./bin/activate
pip install -U -q slacker-cli
pip install -U -q gdown
pip install -U -q pygithub3
pip install -U -q gdown
pip install -U -q percol
pip install -U -q freezegun
pip install -U -q tabulate
source /opt/ros/kinetic/setup.bash
python -v
>>> import cv2
>>> import cv2
dlopen("/opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so", 2);
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
>>> sys.path
['', '/opt/ros/kinetic/lib/python2.7/dist-packages', '/tmp/venv/lib/python2.7', '/tmp/venv/lib/python2.7/plat-x86_64-linux-gnu', '/tmp/venv/lib/python2.7/lib-tk', '/tmp/venv/lib/python2.7/lib-old', '/tmp/venv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/tmp/venv/local/lib/python2.7/site-packages', '/tmp/venv/lib/python2.7/site-packages']
```
Do they decided not to load from system path?

**Comment by wkentaro** [comment]
Actually, I fixed the error of `numpy.core.multiarray failed to import` by 10d0c6a.
But I can't fix the problem of `KeyboardInterruptedError` in https://github.com/jsk-ros-pkg/jsk_common/pull/1599#issuecomment-417914822.

**Comment by k-okada** [comment]
` KeyboardInterruptedError` raised because of sending "C-c" signal when the test was stopped, I think.

**Comment by wkentaro** [comment]
Thank you. I found the fix.
23ab4d5 fixes it. I missed node_scripts to install.

**Comment by wkentaro** [comment]
Now the test passes, and this pr is ready to be merged. Could you merge this? @k-okada

**Comment by k-okada** [comment]
thank you!

**Pull request merged**
